export type UnidadePeriodoContrato='dia'|'semana'|'mes'|'ano';export type ModalidadeTransporteContrato='sem_transporte'|'taxidog'
export type ItemVendaContrato={pacoteServicoId:string;servicoId:string;servicoNome:string;ordem:number;quantidadePorCiclo:number;intervaloQuantidade:number;intervaloUnidade:UnidadePeriodoContrato;offsetInicialQuantidade:number;offsetInicialUnidade:UnidadePeriodoContrato}
export type IntencaoVendaContrato={chaveIdempotencia:string;clienteId:string;petId:string;pacoteId:string;pacoteVersaoEsperada:number;valorContratado:number;motivoAjusteValor:string|null;dataAncora:string;diaSemanaFixo:number;horarioFixo:string;modalidadeTransporte:ModalidadeTransporteContrato;taxidogCicloId:string|null;funcionarioResponsavelId:string;renovacaoAutomatica:boolean}
export type ContratoResumo={id:string;clienteId:string;petId:string;clienteNome:string;petNome:string;pacoteNome:string;status:string;cicloEstado?:'reservado'|'requer_revisao'|'em_andamento'|'concluido'|'cancelado'|null;valorContratado:number;dataAncora:string;diaSemanaFixo:number;horarioFixo:string;modalidadeTransporte:ModalidadeTransporteContrato;renovacaoAutomatica:boolean;criadoEm:string;itens:ItemVendaContrato[]}
export type RespostaVendaContrato=
  |{status:'criado';contrato:ContratoResumo;materializacao:{cicloId:string;quantidadeAtendimentos:number}}
  |{status:'materializacao_pendente';contrato:ContratoResumo;cicloId:string;codigo:string;mensagem:string}
  |{status:'conflito'|'invalido';codigo:string;mensagem:string}
export function lerIntencaoVendaContrato(v:unknown):IntencaoVendaContrato|null{if(!obj(v)||!uuid(v.chaveIdempotencia)||!texto(v.clienteId,128)||!texto(v.petId,128)||!uuid(v.pacoteId)||!uuid(v.funcionarioResponsavelId))return null;if(!inteiro(v.pacoteVersaoEsperada,0)||!dinheiro(v.valorContratado)||!data(v.dataAncora)||!inteiro(v.diaSemanaFixo,0,6))return null;if(typeof v.horarioFixo!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.horarioFixo))return null;if(v.modalidadeTransporte!=='sem_transporte'&&v.modalidadeTransporte!=='taxidog')return null;const ciclo=v.taxidogCicloId==null?null:uuid(v.taxidogCicloId)?v.taxidogCicloId:null;if((v.modalidadeTransporte==='taxidog'&&!ciclo)||(v.modalidadeTransporte==='sem_transporte'&&ciclo)||typeof v.renovacaoAutomatica!=='boolean')return null;const motivo=typeof v.motivoAjusteValor==='string'&&v.motivoAjusteValor.trim()?v.motivoAjusteValor.trim():null;return{chaveIdempotencia:v.chaveIdempotencia,clienteId:v.clienteId.trim(),petId:v.petId.trim(),pacoteId:v.pacoteId,pacoteVersaoEsperada:v.pacoteVersaoEsperada,valorContratado:v.valorContratado,motivoAjusteValor:motivo,dataAncora:v.dataAncora,diaSemanaFixo:v.diaSemanaFixo,horarioFixo:v.horarioFixo,modalidadeTransporte:v.modalidadeTransporte,taxidogCicloId:ciclo,funcionarioResponsavelId:v.funcionarioResponsavelId,renovacaoAutomatica:v.renovacaoAutomatica}}
export function validarDiaAncora(dataIso:string,dia:number){const[a,m,d]=dataIso.split('-').map(Number);return new Date(Date.UTC(a,m-1,d)).getUTCDay()===dia}
function obj(v:unknown):v is Record<string,unknown>{return Boolean(v)&&typeof v==='object'&&!Array.isArray(v)}function uuid(v:unknown):v is string{return typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v)}function texto(v:unknown,max:number):v is string{return typeof v==='string'&&v.trim().length>0&&v.length<=max}function inteiro(v:unknown,min:number,max=Number.MAX_SAFE_INTEGER):v is number{return typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=max}function dinheiro(v:unknown):v is number{return typeof v==='number'&&Number.isFinite(v)&&v>=0&&Math.round(v*100)===v*100}function data(v:unknown):v is string{return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(`${v}T00:00:00Z`))}
