export type CriterioPrecificacao = 'porte' | 'pelagem' | 'raca' | 'peso' | 'temperamento'
export type PerfilPrecificacao = { porte:string;pelagem:string;racaId:string;racaNome:string;peso:number|null;temperamento:string }
export type RegraPrecificacao = { id:string;servicoId:string;criterio:CriterioPrecificacao;porte:string|null;pelagem:string|null;racaId:string|null;pesoMin:number|null;pesoMax:number|null;temperamento:string|null;acrescimoValor:number;ativo:boolean }
export type ServicoResolvidoPrecificacao = { id:string;nome:string;origem:'solicitado'|'dependencia';ordem:number;paisDiretos:string[] }
export type DadosPrecificacaoCompartilhados = { servicos:{id:string;nome:string;precoBase:number;ativo:boolean}[];regrasPreco:RegraPrecificacao[] }
export type ResultadoPrecificacaoCompartilhado = { servicos:{servicoId:string;servicoNome:string;origem:'solicitado'|'dependencia';ordem:number;paisDiretos:string[];precoBaseSnapshot:number;acrescimos:{regraPrecoId:string;criterio:CriterioPrecificacao;descricaoSnapshot:string;valorReferenciaSnapshot:string;acrescimoValor:number}[];valorCalculado:number}[];valorCalculadoAtendimento:number }
export type PacotePrecificavel = { id:string;versao:number;servicos:{id?:string;servicoId:string;servicoNome?:string;quantidadePorCiclo:number;descontoPercentual:number|null}[] }
export type ComparacaoPacoteCompartilhada = { pacoteId:string;pacoteVersao:number;linhas:{pacoteServicoId:string;servicoId:string;servicoNome:string;quantidadePorCiclo:number;descontoPercentual:number;precoAvulsoUnitario:number;precoPacoteUnitario:number;totalAvulso:number;totalPacote:number;economia:number}[];totalAvulso:number;totalPacote:number;economiaAbsoluta:number;percentualEconomia:number|null }
export function normalizarDescontoPercentual(valor:unknown):number|null{if(valor==null)return null;const percentual=typeof valor==='number'?valor:typeof valor==='string'&&valor.trim()!==''?Number(valor):Number.NaN;if(!Number.isFinite(percentual)||percentual<0||percentual>100)throw new Error('Desconto percentual inválido no Pacote.');return percentual}

export function calcularPrecificacaoCompartilhada(pet:PerfilPrecificacao,servicosResolvidos:ServicoResolvidoPrecificacao[],dados:DadosPrecificacaoCompartilhados):ResultadoPrecificacaoCompartilhado{
  const servicos=servicosResolvidos.map((resolvido)=>{const configurado=dados.servicos.find((item)=>item.id===resolvido.id);if(!configurado?.ativo)throw new Error(`Serviço indisponível para precificação: ${resolvido.id}.`);const precoBaseSnapshot=emReais(emCentavos(configurado.precoBase));const acrescimos=dados.regrasPreco.filter((regra)=>regra.ativo&&regra.servicoId===resolvido.id&&regraAplicavel(regra,pet)).sort((a,b)=>compararIds(a.id,b.id)).map((regra)=>materializarAcrescimo(regra,pet));const totalCentavos=emCentavos(precoBaseSnapshot)+acrescimos.reduce((total,item)=>total+emCentavos(item.acrescimoValor),0);return{servicoId:resolvido.id,servicoNome:resolvido.nome,origem:resolvido.origem,ordem:resolvido.ordem,paisDiretos:[...resolvido.paisDiretos],precoBaseSnapshot,acrescimos,valorCalculado:emReais(totalCentavos)}});return{servicos,valorCalculadoAtendimento:emReais(servicos.reduce((total,item)=>total+emCentavos(item.valorCalculado),0))}
}
export function calcularComparacaoPacoteCompartilhada(pacote:PacotePrecificavel,_pet:PerfilPrecificacao,avulso:ResultadoPrecificacaoCompartilhado):ComparacaoPacoteCompartilhada{
  const linhas=pacote.servicos.map((item)=>{const oficial=avulso.servicos.find((servico)=>servico.servicoId===item.servicoId);if(!oficial)throw new Error(`Servico sem preco avulso: ${item.servicoId}`);if(item.descontoPercentual===null||item.descontoPercentual<0||item.descontoPercentual>100)throw new Error(`Pacote requer revisão comercial: ${item.servicoId}`);const avulsoCentavos=emCentavos(oficial.valorCalculado);const precoPacoteUnitario=emReais(Math.round(avulsoCentavos*(100-item.descontoPercentual)/100));const totalAvulso=emReais(avulsoCentavos*item.quantidadePorCiclo);const totalPacote=emReais(emCentavos(precoPacoteUnitario)*item.quantidadePorCiclo);return{pacoteServicoId:item.id??'',servicoId:item.servicoId,servicoNome:item.servicoNome??oficial.servicoNome,quantidadePorCiclo:item.quantidadePorCiclo,descontoPercentual:item.descontoPercentual,precoAvulsoUnitario:oficial.valorCalculado,precoPacoteUnitario,totalAvulso,totalPacote,economia:emReais(emCentavos(totalAvulso)-emCentavos(totalPacote))}});const totalAvulso=emReais(linhas.reduce((s,l)=>s+emCentavos(l.totalAvulso),0)),totalPacote=emReais(linhas.reduce((s,l)=>s+emCentavos(l.totalPacote),0)),economiaAbsoluta=emReais(emCentavos(totalAvulso)-emCentavos(totalPacote));return{pacoteId:pacote.id,pacoteVersao:pacote.versao,linhas,totalAvulso,totalPacote,economiaAbsoluta,percentualEconomia:totalAvulso===0?null:Math.round((economiaAbsoluta/totalAvulso)*10000)/100}
}
function regraAplicavel(regra:RegraPrecificacao,pet:PerfilPrecificacao){if(regra.criterio==='porte')return regra.porte===pet.porte;if(regra.criterio==='pelagem')return regra.pelagem===pet.pelagem;if(regra.criterio==='raca')return regra.racaId===pet.racaId;if(regra.criterio==='temperamento')return regra.temperamento===pet.temperamento;if(pet.peso===null)return false;return(regra.pesoMin===null||pet.peso>=regra.pesoMin)&&(regra.pesoMax===null||pet.peso<=regra.pesoMax)}
function materializarAcrescimo(regra:RegraPrecificacao,pet:PerfilPrecificacao){const referencias={porte:pet.porte,pelagem:pet.pelagem,raca:pet.racaNome,peso:pet.peso===null?'':String(pet.peso),temperamento:pet.temperamento},descricoes={porte:'Acréscimo por porte',pelagem:'Acréscimo por pelagem',raca:'Acréscimo por raça',peso:'Acréscimo por peso',temperamento:'Acréscimo por temperamento'};return{regraPrecoId:regra.id,criterio:regra.criterio,descricaoSnapshot:descricoes[regra.criterio],valorReferenciaSnapshot:referencias[regra.criterio],acrescimoValor:emReais(emCentavos(regra.acrescimoValor))}}
function emCentavos(valor:number){if(!Number.isFinite(valor)||valor<0)throw new Error('Valor monetário inválido para precificação.');return Math.round((valor+Number.EPSILON)*100)}function emReais(centavos:number){return centavos/100}function compararIds(a:string,b:string){return a<b?-1:a>b?1:0}
