import type { SupabaseClient } from 'npm:@supabase/supabase-js@2.112.2'
import {
  calcularComparacaoPacoteCompartilhada,
  calcularPrecificacaoCompartilhada,
  normalizarDescontoPercentual,
} from './precificacao.ts'
import type {
  ComparacaoPacoteCompartilhada,
  DadosPrecificacaoCompartilhados,
  PacotePrecificavel,
  PerfilPrecificacao,
  RegraPrecificacao,
} from './precificacao.ts'
import { ErroCadastroPetIncompletoPrecificacao } from './precificacao.ts'
export type RespostaSimulacaoPacoteCompartilhada={status:'calculado';simulacao:ComparacaoPacoteCompartilhada}|{status:'conflito'|'invalido';codigo:string;mensagem:string;campos?:string[]}
type ItemCarregado=PacotePrecificavel['servicos'][number]&{servicoNome:string;ordem:number;intervaloQuantidade:number;intervaloUnidade:string;offsetInicialQuantidade:number;offsetInicialUnidade:string}
type PacoteCarregado=Omit<PacotePrecificavel,'servicos'>&{nome:string;ativo:boolean;configuracaoCompleta:boolean;servicos:ItemCarregado[]};type Linha=Record<string,unknown>
const consulta='id,nome,ativo,versao,pacote_servicos(id,servico_id,ordem_exibicao,quantidade_por_ciclo,intervalo_quantidade,intervalo_unidade,offset_inicial_quantidade,offset_inicial_unidade,desconto_percentual,ativo,servicos(nome))'
export async function executarSimulacaoPacote(i:{pacoteId:string;pacoteVersaoEsperada:number;petId:string},admin:SupabaseClient):Promise<RespostaSimulacaoPacoteCompartilhada>{const[{data,error},precos]=await Promise.all([admin.from('pacotes').select(consulta).eq('id',i.pacoteId).single(),carregarPrecos(i.petId,admin)]);if(error||!data)return{status:'invalido',codigo:'PACOTE_NAO_ENCONTRADO',mensagem:'Pacote não encontrado.'};const pacote=mapear(data as unknown as Linha);if(pacote.versao!==i.pacoteVersaoEsperada)return{status:'conflito',codigo:'VERSAO_DIVERGENTE',mensagem:'O Pacote mudou. Recarregue antes de comparar.'};if(!pacote.servicos.length)return{status:'invalido',codigo:'COMPOSICAO_OBRIGATORIA',mensagem:'Configure os Serviços antes de simular.'};if(!pacote.configuracaoCompleta)return{status:'invalido',codigo:'PACOTE_REQUER_REVISAO',mensagem:'Revise os descontos deste Pacote antes de simular.'};const resolvidos=pacote.servicos.map(s=>({id:s.servicoId,nome:s.servicoNome,origem:'solicitado'as const,ordem:s.ordem,paisDiretos:[]}));try{const avulso=calcularPrecificacaoCompartilhada(precos.pet,resolvidos,precos.dados);return{status:'calculado',simulacao:calcularComparacaoPacoteCompartilhada(pacote,precos.pet,avulso)}}catch(erro){if(erro instanceof ErroCadastroPetIncompletoPrecificacao)return{status:'invalido',codigo:'CADASTRO_PET_INCOMPLETO',mensagem:erro.message,campos:erro.campos};throw erro}}
function mapear(l:Linha):PacoteCarregado{const servicos=(Array.isArray(l.pacote_servicos)?l.pacote_servicos:[]).filter(x=>Boolean((x as Linha).ativo)).map(x=>item(x as Linha)).sort((a,b)=>a.ordem-b.ordem);return{id:String(l.id),nome:String(l.nome),ativo:Boolean(l.ativo),versao:Number(l.versao),configuracaoCompleta:Boolean(servicos.length&&servicos.every(x=>x.descontoPercentual!==null)),servicos}}
function item(l:Linha):ItemCarregado{const s=Array.isArray(l.servicos)?l.servicos[0]as Linha|undefined:l.servicos as Linha|undefined;return{id:String(l.id),servicoId:String(l.servico_id),servicoNome:String(s?.nome??''),ordem:Number(l.ordem_exibicao),quantidadePorCiclo:Number(l.quantidade_por_ciclo),intervaloQuantidade:Number(l.intervalo_quantidade),intervaloUnidade:String(l.intervalo_unidade),offsetInicialQuantidade:Number(l.offset_inicial_quantidade),offsetInicialUnidade:String(l.offset_inicial_unidade),descontoPercentual:normalizarDescontoPercentual(l.desconto_percentual)}}
async function carregarPrecos(petId:string,admin:SupabaseClient):Promise<{pet:PerfilPrecificacao;dados:DadosPrecificacaoCompartilhados}>{const[p,s,r]=await Promise.all([admin.from('pets').select('id,raca_id,porte,pelagem,peso,temperamento,raca:racas!pets_raca_especie_fkey(nome)').eq('id',petId).single(),admin.from('servicos').select('id,nome,preco_base,ativo'),admin.from('servico_regras_preco').select('id,servico_id,criterio,porte,pelagem,raca_id,peso_min,peso_max,temperamento,acrescimo_valor,ativo')]);if(p.error||s.error||r.error)throw new Error('Dados autoritativos de preço indisponíveis.');const x=p.data as unknown as Linha,ra=Array.isArray(x.raca)?x.raca[0]as Linha|undefined:x.raca as Linha|undefined;return{pet:{racaId:n(x.raca_id),racaNome:n(ra?.nome),porte:n(x.porte),pelagem:n(x.pelagem),peso:x.peso==null?null:Number(x.peso),temperamento:n(x.temperamento)},dados:{servicos:((s.data??[])as unknown as Linha[]).map(x=>({id:String(x.id),nome:String(x.nome),precoBase:Number(x.preco_base),ativo:Boolean(x.ativo)})),regrasPreco:((r.data??[])as unknown as Linha[]).map(x=>({id:String(x.id),servicoId:String(x.servico_id),criterio:String(x.criterio)as RegraPrecificacao['criterio'],porte:n(x.porte),pelagem:n(x.pelagem),racaId:n(x.raca_id),pesoMin:nn(x.peso_min),pesoMax:nn(x.peso_max),temperamento:n(x.temperamento),acrescimoValor:Number(x.acrescimo_valor),ativo:Boolean(x.ativo)}))}}}
function n(v:unknown){return v==null?null:String(v)}function nn(v:unknown){return v==null?null:Number(v)}
