import assert from 'node:assert/strict'
import fs from 'node:fs'
import { buscarClientes, construirEntradaNovoAgendamento, criarControleConsultas, diasDoCalendario, deslocarMes, horariosDoResultado, petsDoCliente } from './novoAgendamento.ts'
import type { Cliente } from '../types/Cliente.ts'
import type { Pet } from '../types/Pet.ts'
import type { ResultadoDisponibilidade } from '../motorDisponibilidade/tipos.ts'
import { resumirDisponibilidadeDoCiclo } from '../motorDisponibilidade/ciclo.ts'

let aprovados = 0
function teste(codigo: string, nome: string, executar: () => void) { executar(); aprovados += 1; console.log(`${codigo} — ${nome}: OK`) }
const cliente = (id: string, nome: string, whatsapp = ''): Cliente => ({ id, nome, whatsapp, endereco: '', bairro: '', cidade: '', observacoes: '', criadoEm: '' })
const pet = (id: string, clienteId: string, nome: string): Pet => ({ id, clienteId, nome, especie: 'cao', racaId: 'r', racaNome: 'SRD', sexo: 'macho', porte: 'pequeno', pelagem: 'curta', peso: 8, cor: '', dataNascimento: '', castrado: false, temperamento: 'calmo', observacoes: '', criadoEm: '' })
const fonteAgenda = fs.readFileSync(new URL('../pages/Agenda.tsx', import.meta.url), 'utf8')
const fonteModal = fs.readFileSync(new URL('./NovoAgendamentoModal.tsx', import.meta.url), 'utf8')
const fonteDev = fs.readFileSync(new URL('../pages/TesteMotorDisponibilidade.tsx', import.meta.url), 'utf8')
const fonteServicoEdge = fs.readFileSync(new URL('../../../supabase/functions/confirmar-agendamento/servico.ts', import.meta.url), 'utf8')

teste('NA01', 'grade abre o fluxo oficial', () => assert.ok(fonteAgenda.includes('novo={abrirNovo}') && fonteAgenda.includes('setNovoAberto(true)')))
teste('NA02', 'data inicial vem da Agenda', () => assert.ok(fonteAgenda.includes('dataInicial={data}') && fonteModal.includes('useState(dataInicial)')))
teste('NA03', 'busca cliente por nome e telefone com limite', () => { const itens = [cliente('1', 'João', '111'), cliente('2', 'Maria', '222')]; assert.deepEqual(buscarClientes(itens, '111').map((i) => i.id), ['1']); assert.deepEqual(buscarClientes(itens, 'maria').map((i) => i.id), ['2']); assert.equal(buscarClientes(Array.from({ length: 12 }, (_, i) => cliente(String(i), `Cliente ${i}`)), 'cliente').length, 8) })
teste('NA04', 'seleção de cliente é explícita', () => assert.ok(fonteModal.includes('selecionar={selecionarCliente}') && fonteModal.includes('onClick={() => selecionar(item)}') && fonteModal.includes('Cliente selecionado')))
teste('NA05', 'pets são filtrados pelo cliente', () => assert.deepEqual(petsDoCliente([pet('2', 'b', 'Bia'), pet('1', 'a', 'Zeca'), pet('3', 'a', 'Ana')], 'a').map((i) => i.id), ['3', '1']))
teste('NA06', 'pet único pode ser selecionado', () => assert.ok(fonteModal.includes('onClick={() => selecionar(pet.id)}') && fonteModal.includes("setPetId(id)")))
teste('NA07', 'somente serviços ativos são apresentados', () => assert.ok(fonteModal.includes("agenda.servicos.filter((item) => item.ativo)")))
teste('NA08', 'múltiplos serviços são preservados deterministicamente', () => assert.deepEqual(construirEntradaNovoAgendamento({ petId: 'p', servicoIds: ['z', 'a'], data: '2026-08-15', modalidade: 'sem_transporte', cicloTaxidogId: '', funcionarioResponsavelId:'f1' }).servicoIds, ['a', 'z']))
teste('NA09', 'modalidade usa contrato existente', () => { assert.equal(construirEntradaNovoAgendamento({ petId: 'p', servicoIds: ['s'], data: '2026-08-15', modalidade: 'sem_transporte', cicloTaxidogId: 'x', funcionarioResponsavelId:'f1' }).cicloTaxidogId, null); assert.equal(construirEntradaNovoAgendamento({ petId: 'p', servicoIds: ['s'], data: '2026-08-15', modalidade: 'taxidog', cicloTaxidogId: 'x', funcionarioResponsavelId:'f1' }).cicloTaxidogId, 'x') })
teste('NA10', 'consulta usa API pública real do Motor', () => assert.ok(fonteModal.includes('const entrada = construirEntradaNovoAgendamento(') && fonteModal.includes('consultarDisponibilidade(entrada)')))
teste('NA11', 'somente horários retornados são expostos', () => { const resultado = { estado: 'OK', opcoes: [{ horarioApresentado: 540 }, { horarioApresentado: 615 }] } as ResultadoDisponibilidade; assert.deepEqual(horariosDoResultado(resultado), [540, 615]) })
teste('NA12', 'horário seleciona exatamente a opção do Motor', () => assert.ok(fonteModal.includes('onClick={() => selecionar(item)}') && fonteModal.includes('selecionar={setOpcao}')))
teste('NA13', 'revisão mostra identidade e planejamento', () => assert.ok(fonteModal.includes('Revisar agendamento') && fonteModal.includes('Planejamento operacional') && fonteModal.includes('Tutor: {cliente.nome}')))
teste('NA14', 'mudança de parâmetros invalida resultado e loading', () => assert.ok(fonteModal.includes('function invalidarResultado()') && fonteModal.includes('setResultado(null)') && fonteModal.includes('setOpcao(null)') && fonteModal.includes('setConsultando(false)')))
teste('NA15', 'resposta assíncrona antiga é descartada', () => { const controle = criarControleConsultas(); const antiga = controle.iniciar(); const nova = controle.iniciar(); assert.equal(controle.atual(antiga), false); assert.equal(controle.atual(nova), true); controle.invalidar(); assert.equal(controle.atual(nova), false) })
teste('NA16', 'estado sem disponibilidade é explícito', () => assert.ok(fonteModal.includes('Nenhum horário disponível') && fonteModal.includes('resultado ? <div className="novo-sem-horarios"')))
teste('NA17', 'erro de consulta permite tentar novamente', () => assert.ok(fonteModal.includes('Não foi possível consultar') && fonteModal.includes('Tentar novamente')))
teste('NA18', 'fluxo não realiza escrita', () => assert.ok(!/\.\s*(insert|update|delete|upsert)\s*\(/.test(fonteModal)))
teste('NA19', 'fluxo confirma somente pelo cliente autoritativo', () => assert.ok(fonteModal.includes('confirmacaoAgendamentoClient.confirmar') && !/\.\s*(insert|update|delete|upsert)\s*\(/.test(fonteModal)))
teste('NA20', 'ferramentas DEV permanecem separadas', () => assert.ok(fonteDev.includes('ConfirmacaoAgendamentoDev') && fonteDev.includes('PlanejamentoLoteDev') && !fonteAgenda.includes('ConfirmacaoAgendamentoDev')))

teste('NA21', 'calendário mensal possui grade fixa e navegação entre anos', () => { assert.equal(diasDoCalendario(2026, 7).length, 42); assert.deepEqual(deslocarMes(2026, 11, 1), { ano: 2027, mes: 0 }); assert.deepEqual(deslocarMes(2026, 0, -1), { ano: 2025, mes: 11 }) })
teste('NA22', 'horários reais são agrupados sem entrada manual', () => assert.ok(fonteModal.includes("titulo: 'Manhã'") && fonteModal.includes("titulo: 'Tarde'") && !fonteModal.includes('type="time"')))
teste('NA23', 'fluxo possui seis etapas independentes', () => assert.ok(fonteModal.includes('type EtapaFluxo = 1 | 2 | 3 | 4 | 5 | 6') && fonteModal.includes('etapa === 4 ? <EtapaTransporte') && fonteModal.includes('etapa === 5 ? <EtapaDataHorarios')))
teste('NA24', 'serviços não contém controles de transporte', () => { const trecho = fonteModal.slice(fonteModal.indexOf('function EtapaServicos'), fonteModal.indexOf('function EtapaTransporte')); assert.ok(!trecho.includes('novo-modalidade') && !trecho.includes('TaxiDog') && trecho.includes('novo-servicos-visuais')) })
teste('NA25', 'TaxiDog exige ciclo antes de avançar', () => assert.ok(fonteModal.includes("modalidade === 'taxidog' && cicloTaxidogId") && fonteModal.includes("modalidadeConsulta === 'taxidog' && !cicloConsulta")))
teste('NA26', 'troca de modalidade limpa ciclo e disponibilidade', () => assert.ok(fonteModal.includes("setModalidade(valor); setCicloTaxidogId(''); invalidarResultado()")))
teste('NA27', 'resumos mostram transporte, responsável e ciclo', () => assert.ok(fonteModal.includes("titulo: 'Transporte e responsável'") && fonteModal.includes('Como o pet chegará até nós') && fonteModal.includes('Ciclo: ${cicloNome}')))
teste('NA28', 'sem transporte mantém grade e seleção explícita', () => assert.ok(fonteModal.includes("modalidade === 'taxidog') return") && fonteModal.includes('<Horarios opcoes={resultado.opcoes}') && fonteModal.includes('etapa === 5 ? opcao')))
teste('NA29', 'TaxiDog mantém horários relevantes visíveis com estados distintos', () => { const trecho = fonteModal.slice(fonteModal.indexOf('function PainelHorariosTaxidog'), fonteModal.indexOf('function Calendario')); assert.ok(trecho.includes('Fora da janela do TaxiDog') && trecho.includes('Sem capacidade') && trecho.includes('disabled={!habilitado}')) })
teste('NA30', 'disponibilidade do ciclo exige solução real', () => { const vazio = resumirDisponibilidadeDoCiclo({ estado: 'SEM_DISPONIBILIDADE', data: '2026-08-18', opcoes: [], motivos: ['sem solução'] }); assert.equal(vazio.disponivel, false); assert.equal(vazio.opcao, null) })
teste('NA31', 'solução interna preserva a primeira opção ordenada pelo Motor', () => { const primeira = { horarioApresentado: 600 } as ResultadoDisponibilidade['opcoes'][number]; const segunda = { horarioApresentado: 540 } as ResultadoDisponibilidade['opcoes'][number]; const ciclo = resumirDisponibilidadeDoCiclo({ estado: 'OK', data: '2026-08-18', opcoes: [primeira, segunda], motivos: [] }); assert.equal(ciclo.disponivel, true); assert.equal(ciclo.opcao, primeira) })
teste('NA32', 'consulta TaxiDog usa o Motor para janela e horários relevantes', () => assert.ok(fonteModal.includes('consultarDisponibilidadeDoCiclo(entrada)') && fonteModal.includes('consultarDisponibilidade(entradaSemTransporte)')))
teste('NA33', 'trocas invalidam solução de ciclo', () => assert.ok(fonteModal.includes('setResultadoCiclo(null)') && fonteModal.includes("setCicloTaxidogId(''); invalidarResultado()")))
teste('NA34', 'revisão TaxiDog prioriza ciclo e coleta', () => assert.ok(fonteModal.includes("if (modalidade === 'taxidog') return <EtapaCabecalho") && fonteModal.includes('Data operacional') && fonteModal.includes('Coleta {minutosParaHora(opcao.cicloTaxidog.coletaInicio)}')))
teste('NA35', 'revisão TaxiDog não destaca horário interno', () => { const revisao = fonteModal.indexOf('function EtapaRevisao'); const inicio = fonteModal.indexOf("if (modalidade === 'taxidog') return <EtapaCabecalho", revisao); const fim = fonteModal.indexOf("return <EtapaCabecalho numero=\"06\"", inicio + 1); const trecho = fonteModal.slice(inicio, fim); assert.ok(fim > inicio && !trecho.includes('horarioApresentado') && !trecho.includes('inicioOperacional')) })
teste('NA36', 'erro do Motor não vira disponibilidade', () => assert.ok(fonteModal.includes('if (erro) return') && fonteModal.includes('Boolean(resultado?.disponivel&&resultado.opcao)')))
teste('NA37', 'duplo clique é bloqueado no frontend', () => assert.ok(fonteModal.includes('confirmacaoEmAndamento.current') && fonteModal.includes('disabled={confirmando}')))
teste('NA38', 'tentativa preserva idempotência em retry seguro', () => assert.ok(fonteModal.includes('montarIntencaoConfirmacao(') && fonteModal.includes('setTentativa(montada.tentativa)')))
teste('NA39', 'conflitos retornam à disponibilidade sem troca automática', () => assert.ok(fonteModal.includes("setEtapa(5)") && fonteModal.includes('Este horário não está mais disponível.') && fonteModal.includes('Não há mais disponibilidade neste ciclo')))
teste('NA40', 'sucesso recarrega Agenda e fecha modal', () => assert.ok(fonteAgenda.includes('await carregar(dataConfirmada)') && fonteAgenda.includes('setNovoAberto(false)') && fonteAgenda.includes('onConfirmado={concluirNovoAgendamento}')))
teste('NA41', 'versões pertencem à consulta apresentada', () => assert.ok(fonteModal.includes('carregarVersoesConfirmacao()') && fonteModal.includes('setVersoes(versoesConsulta)') && fonteModal.includes('setVersoes(null)')))
teste('NA42', 'preço não é enviado como autoridade', () => assert.ok(!fonteModal.includes('valorFinal:') && !fonteModal.includes('valorCalculado:')))
teste('NA43', 'estado de processamento bloqueia navegação final', () => assert.ok(fonteModal.includes("confirmando ? 'Confirmando agendamento...' : 'Confirmar agendamento'") && fonteModal.includes('disabled={confirmando}>Voltar')))
teste('NA44', 'erro técnico externo é sanitizado', () => assert.ok(fonteModal.includes('Não foi possível confirmar o agendamento. Verifique a conexão e tente novamente.') && !fonteModal.includes('stack')))
teste('NA45', 'Sem transporte apresenta Valor do atendimento', () => assert.ok(fonteModal.includes('<BlocoValor preco={preco}') && fonteModal.includes('Valor do atendimento')))
teste('NA46', 'TaxiDog apresenta o mesmo bloco de valor', () => { const inicio = fonteModal.indexOf("if (modalidade === 'taxidog') return"); assert.ok(fonteModal.slice(inicio).includes('{valor}</EtapaCabecalho>')) })
teste('NA47', 'valor usa infraestrutura financeira existente', () => assert.ok(fonteModal.includes('carregarDadosPrecificacaoComCliente(petId, supabase)') && fonteModal.includes('calcularPrecificacao(dadosPreco.pet, opcaoAtual.servicos, dadosPreco.dados)')))
teste('NA48', 'modal não contém fórmula financeira duplicada', () => assert.ok(!fonteModal.includes('precoBase +') && !fonteModal.includes('reduce((total, regra)')))
teste('NA49', 'valor apresentado não entra na intenção', () => { const inicio = fonteModal.indexOf('montarIntencaoConfirmacao({'); const fim = fonteModal.indexOf('}, tentativa)', inicio); assert.ok(!fonteModal.slice(inicio, fim).includes('preco') && !fonteModal.slice(inicio, fim).includes('valor')) })
teste('NA50', 'Edge continua recalculando preço', () => assert.ok(fonteServicoEdge.includes('carregarDadosPrecificacaoComCliente(intencao.petId, admin)') && fonteServicoEdge.includes('calcularPrecificacao(precos.pet, opcao.servicos, precos.dados)')))
teste('NA51', 'mudança de pet invalida preço', () => assert.ok(fonteModal.includes("setPetId(id); invalidarResultado()") && fonteModal.includes("setPreco({ status: 'inativo' })")))
teste('NA52', 'mudança de serviço invalida preço', () => assert.ok(fonteModal.includes('function alterarServico') && fonteModal.includes('invalidarResultado()')))
teste('NA53', 'mudança de modalidade ou ciclo invalida preço', () => assert.ok(fonteModal.includes("setModalidade(valor); setCicloTaxidogId(''); invalidarResultado()") && fonteModal.includes('alterarCiclo={(id) => { setCicloTaxidogId(id); invalidarResultado() }}')))
teste('NA54', 'zero é preço válido', () => { const prontoZero: { status: 'pronto'; valor: number } = { status: 'pronto', valor: 0 }; assert.equal(prontoZero.status, 'pronto'); assert.equal(prontoZero.valor, 0) })
teste('NA55', 'erro financeiro não vira zero e preserva erro de cadastro', () => assert.ok(fonteModal.includes("setPreco({ status: 'erro',mensagem:") && fonteModal.includes('error instanceof ErroCadastroPetIncompleto?error.message:undefined') && fonteModal.includes('Não foi possível calcular o valor do atendimento.') && !fonteModal.includes("status: 'erro', valor: 0")))
teste('NA56', 'carregamento financeiro é explícito', () => assert.ok(fonteModal.includes("setPreco({ status: 'carregando' })") && fonteModal.includes('Calculando valor...')))
teste('NA57', 'confirmação exige preço válido', () => assert.ok(fonteModal.includes("preco.status !== 'pronto'") && fonteModal.includes("podeConfirmar={preco.status === 'pronto'}")))
teste('NA58', 'Agenda continua usando valor final persistido', () => assert.ok(fonteAgenda.includes('moeda(atendimento.valorFinal)') && fonteAgenda.includes('carregarAgendaDiaria')))
teste('NA59','janela TaxiDog permanece separada do início efetivo',()=>assert.ok(fonteModal.includes('janela logística pode ter execução efetiva posterior')&&fonteModal.includes('resultado.opcao')))
teste('NA60','troca para TaxiDog invalida opção incompatível',()=>assert.ok(fonteModal.includes("setModalidade(valor); setCicloTaxidogId(''); invalidarResultado()")))
teste('NA61','responsável é obrigatório e validado pelo Motor',()=>assert.ok(fonteModal.includes("preferenciaFuncionario: 'obrigatorio'")&&fonteModal.includes('Escolha o funcionário responsável.')))
teste('NA62','pet incompleto não é bloqueado antes dos serviços',()=>assert.ok(!fonteModal.includes('pendenciasPet(pet)')&&fonteModal.includes('CADASTRO_PET_INCOMPLETO')))
teste('NA63','Edge repete validação estruturada de cadastro',()=>assert.ok(fonteServicoEdge.includes("codigo:'CADASTRO_PET_INCOMPLETO'")&&fonteServicoEdge.includes('campos:resultado.erro.campos')))

console.log(`${aprovados} testes de Novo Agendamento aprovados.`)
