import { useCallback, useEffect, useMemo, useState } from 'react'
import Button from '../components/ui/Button'
import Modal from '../components/ui/Modal'
import type { ContratoResumo } from './contrato'
import type { ContagemCreditos, DetalheCicloCreditos, DetalheUnidadeCredito, EventoCredito, ResumoContratoCreditos, ResumoServicoCredito, UnidadeCredito } from '../../../supabase/functions/_shared/credito-contrato.ts'
import { carregarDetalheCiclo, carregarDetalheCredito, carregarResumoCreditosContrato, decidirCreditoContrato, reverterConclusaoContrato } from './clienteSupabase'

const moeda = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
type Nivel = 'contrato' | 'ciclo' | 'servico' | 'credito'
type Acao = ({ tipo: 'reverter' } | { tipo: 'credito'; operacao: 'decidir_falta' | 'corrigir_decisao' | 'decidir_encerramento'; decisao: 'perder' | 'preservar' }) & { chaveIdempotencia: string }
type NovaAcao = { tipo: 'reverter' } | { tipo: 'credito'; operacao: 'decidir_falta' | 'corrigir_decisao' | 'decidir_encerramento'; decisao: 'perder' | 'preservar' }

export default function DetalheContrato({ contrato, onClose }: { contrato: ContratoResumo; onClose: () => void }) {
  const [nivel, setNivel] = useState<Nivel>('contrato'), [resumo, setResumo] = useState<ResumoContratoCreditos | null>(null), [ciclo, setCiclo] = useState<DetalheCicloCreditos | null>(null), [servico, setServico] = useState<ResumoServicoCredito | null>(null), [credito, setCredito] = useState<DetalheUnidadeCredito | null>(null), [estado, setEstado] = useState<'carregando' | 'pronto' | 'erro'>('carregando'), [erro, setErro] = useState('')
  const carregarResumo = useCallback(async () => { setEstado('carregando'); setErro(''); try { setResumo(await carregarResumoCreditosContrato(contrato.id)); setEstado('pronto') } catch (e) { setErro(mensagem(e)); setEstado('erro') } }, [contrato.id])
  useEffect(() => { void carregarResumo() }, [carregarResumo])
  async function abrirCiclo(id: string) { setEstado('carregando'); setErro(''); try { const detalhe = await carregarDetalheCiclo(id); setCiclo(detalhe); setServico(null); setCredito(null); setNivel('ciclo'); setEstado('pronto') } catch (e) { setErro(mensagem(e)); setEstado('erro') } }
  function abrirServico(item: ResumoServicoCredito) { setServico(item); setCredito(null); setNivel('servico') }
  async function abrirCredito(item: UnidadeCredito) { setEstado('carregando'); setErro(''); try { setCredito(await carregarDetalheCredito(item.ocorrenciaId, item.contratoItemId)); setNivel('credito'); setEstado('pronto') } catch (e) { setErro(mensagem(e)); setEstado('erro') } }
  async function recarregarCredito() { if (!credito) return; const [d, c, r] = await Promise.all([carregarDetalheCredito(credito.ocorrenciaId, credito.contratoItemId), carregarDetalheCiclo(credito.cicloId), carregarResumoCreditosContrato(contrato.id)]); setCredito(d); setCiclo(c); setResumo(r); const atualizado = c.servicos.find((item) => item.contratoItemId === credito.contratoItemId); if (atualizado) setServico(atualizado) }
  function voltar() { if (nivel === 'credito') setNivel('servico'); else if (nivel === 'servico') setNivel('ciclo'); else if (nivel === 'ciclo') setNivel('contrato') }
  const titulo = nivel === 'credito' ? 'Detalhes do crédito' : nivel === 'servico' ? 'Detalhes do serviço' : nivel === 'ciclo' ? `Ciclo ${ciclo?.numero ?? ''}` : 'Detalhes do contrato'
  return <Modal aberto titulo={titulo} onClose={onClose} maxWidth={nivel === 'credito' ? '820px' : '900px'} overlayClassName="contrato-drilldown-overlay" className={`ux-modal contrato-drilldown nivel-${nivel}`}>
    {nivel !== 'contrato' && <nav className="contrato-breadcrumb" aria-label="Navegação do contrato"><button type="button" onClick={voltar}>← {nivel === 'ciclo' ? `Contrato de ${contrato.petNome}` : nivel === 'servico' ? `Ciclo ${ciclo?.numero}` : servico?.nome}</button><span>Contrato <b>›</b> {contrato.petNome}{ciclo ? <><b>›</b> Ciclo {ciclo.numero}</> : null}{servico && ['servico', 'credito'].includes(nivel) ? <><b>›</b><IconeServico nome={servico.nome} compacto /> {servico.nome}</> : null}{credito && nivel === 'credito' ? <><b>›</b> {ordinal(credito.ordinal)} {credito.servicoNome}</> : null}</span></nav>}
    {estado === 'carregando' && <Estado titulo="Carregando…" texto="Buscando informações autoritativas do Contrato." />}
    {estado === 'erro' && <Estado titulo="Não foi possível carregar" texto={erro}><Button onClick={() => void (nivel === 'contrato' ? carregarResumo() : ciclo ? abrirCiclo(ciclo.id) : carregarResumo())}>Tentar novamente</Button></Estado>}
    {estado === 'pronto' && nivel === 'contrato' && resumo && <NivelContrato contrato={contrato} resumo={resumo} abrirCiclo={abrirCiclo} />}
    {estado === 'pronto' && nivel === 'ciclo' && ciclo && <NivelCiclo ciclo={ciclo} abrirServico={abrirServico} />}
    {estado === 'pronto' && nivel === 'servico' && servico && <NivelServico servico={servico} abrirCredito={abrirCredito} />}
    {estado === 'pronto' && nivel === 'credito' && credito && <NivelCredito credito={credito} aposAcao={recarregarCredito} onClose={onClose} />}
  </Modal>
}

function NivelContrato({ contrato, resumo, abrirCiclo }: { contrato: ContratoResumo; resumo: ResumoContratoCreditos; abrirCiclo: (id: string) => void }) {
  const atual = resumo.ciclos.find((item) => item.atual) ?? resumo.ciclos[0]
  return <div className="contrato-nivel-conteudo">
    <section className="contrato-identidade-card"><div className="contrato-avatar-grande" aria-hidden="true">{contrato.petNome.slice(0, 1).toUpperCase()}</div><div className="contrato-identidade-texto"><div><h2>{contrato.petNome}</h2><span className={`ux-status ${contrato.status === 'ativo' ? 'ok' : 'muted'}`}>{contrato.status}</span></div><p>♙ {contrato.clienteNome} <small>(tutor)</small></p><strong>{contrato.pacoteNome}</strong><span>↻ {contrato.renovacaoAutomatica ? 'Renovação automática' : 'Renovação manual'}</span></div><div className="contrato-identidade-valor"><span>Valor por ciclo</span><strong>{moeda.format(contrato.valorContratado)} <small>/ ciclo</small></strong></div></section>
    <section className="contrato-faixa-resumo tres"><Indicador icone={<IconeCiclo compacto />} rotulo="Ciclo atual" valor={atual ? `Ciclo ${atual.numero}` : '—'} /><Indicador icone="◴" rotulo="Consumo geral" valor={`${atual?.consumoPercentual ?? 0}%`} /><Indicador icone="☆" rotulo="Disponíveis" valor={`${atual?.disponiveis ?? 0} créditos`} /></section>
    <TituloSecao titulo="Ciclos" />
    <div className="contrato-ciclos">{resumo.ciclos.map((item) => <button type="button" className={`contrato-ciclo-card ${item.atual ? 'atual' : ''}`} onClick={() => void abrirCiclo(item.id)} key={item.id}><IconeCiclo renovacao grande /><div className="contrato-ciclo-info"><div><strong>Ciclo {item.numero}{item.atual ? ' · Atual' : ''}</strong>{item.atual && <em>Atual</em>}</div><span>{data(item.inicio)} → {data(item.fim)}</span><small>{item.consumidos} de {item.contratados} créditos utilizados</small><BarraSimples contagem={item} /><ResumoInline contagem={item} /></div><i aria-hidden="true">›</i></button>)}</div>
    {!resumo.ciclos.length && <Estado titulo="Nenhum Ciclo" texto="Este Contrato ainda não possui Ciclo no modelo operacional atual." />}
    <div className="contrato-duas-colunas"><section className="contrato-painel-compacto"><h3>Serviços contratados</h3>{contrato.itens.map((item) => <div className="contrato-servico-resumo" key={item.servicoId}><IconeServico nome={item.servicoNome} /><div><strong>{item.servicoNome}</strong><span>{item.quantidadePorCiclo} por ciclo</span><small>A cada {item.intervaloQuantidade} {unidade(item.intervaloUnidade, item.intervaloQuantidade)}</small></div></div>)}</section><section className="contrato-painel-compacto"><h3>Rotina</h3><ListaRotina contrato={contrato} /></section></div>
    <details className="contrato-detalhes-tecnicos"><summary>▤ <span>Informações de registro</span><b>⌄</b></summary><p>Contrato {contrato.id}</p><p>Registrado em {new Date(contrato.criadoEm).toLocaleString('pt-BR')}</p></details>
  </div>
}

function NivelCiclo({ ciclo, abrirServico }: { ciclo: DetalheCicloCreditos; abrirServico: (servico: ResumoServicoCredito) => void }) {
  return <div className="contrato-nivel-conteudo">
    <section className="contrato-ciclo-hero"><IconeCiclo grande /><div><div><h2>Ciclo {ciclo.numero}</h2><TagEstado valor={ciclo.estado} /></div><p>{data(ciclo.inicio)} → {data(ciclo.fim)}</p></div><strong>{ciclo.consumidos} de {ciclo.contratados} utilizados</strong><div className="contrato-faixa-resumo tres"><Indicador icone={<IconeCiclo compacto />} rotulo="Valor do ciclo" valor={ciclo.valor === null ? '—' : moeda.format(ciclo.valor)} /><Indicador icone="◴" rotulo="Consumo geral" valor={`${ciclo.consumoPercentual}%`} /><Indicador icone="☆" rotulo="Disponíveis" valor={String(ciclo.disponiveis)} /></div></section>
    <section className="contrato-progresso-geral"><h3>Progresso geral do ciclo</h3><BarraSimples contagem={ciclo} /><ResumoEstrutural contagem={ciclo} /></section>
    {ciclo.encerramentoPendente && <div className="contrato-aviso"><strong>Encerramento pendente</strong><span>Existem créditos sem destino definitivo neste Ciclo.</span></div>}
    <TituloSecao titulo="Serviços deste ciclo" />
    <div className="contrato-servicos">{ciclo.servicos.map((item) => <button type="button" className="contrato-servico-card" onClick={() => abrirServico(item)} key={item.contratoItemId}><IconeServico nome={item.nome} grande /><div className="contrato-servico-identidade"><strong>{item.nome}</strong><span>{item.consumidos} de {item.contratados} utilizados</span><small>A cada {item.intervaloQuantidade} {unidade(item.intervaloUnidade, item.intervaloQuantidade)}</small></div><BarraSimples contagem={item} /><div className="contrato-servico-percentual"><strong>{item.consumoPercentual}%</strong><span>Restam {item.disponiveis}</span></div><i aria-hidden="true">›</i></button>)}</div>
    <p className="contrato-nota">ⓘ O consumo apresentado respeita o estado comercial atual de cada crédito.</p>
  </div>
}

function NivelServico({ servico, abrirCredito }: { servico: ResumoServicoCredito; abrirCredito: (unidade: UnidadeCredito) => void }) {
  return <div className="contrato-nivel-conteudo">
    <section className="contrato-servico-hero"><IconeServico nome={servico.nome} grande /><div><h2>{servico.nome}</h2><p>A cada {servico.intervaloQuantidade} {unidade(servico.intervaloUnidade, servico.intervaloQuantidade)}</p></div><div><span>Consumo do serviço</span><strong>{servico.consumoPercentual}%</strong><small>consumido</small></div></section>
    <section className="contrato-faixa-resumo quatro"><Indicador icone="▣" rotulo="contratados" valor={String(servico.contratados)} /><Indicador icone="✓" rotulo="consumidos" valor={String(servico.consumidos)} /><Indicador icone="☆" rotulo="disponíveis" valor={String(servico.disponiveis)} /><Indicador icone="∅" rotulo="perdidos" valor={String(servico.perdidos)} /></section>
    <div className="contrato-barra-legenda"><BarraSimples contagem={servico} /><div><span>{servico.consumidos} de {servico.contratados} créditos utilizados</span><span>Restam {servico.disponiveis} créditos</span></div></div>
    <TituloSecao titulo="Créditos deste serviço" />
    <div className="contrato-creditos">{servico.unidades.map((item) => <button type="button" className="contrato-credito-card" onClick={() => void abrirCredito(item)} key={`${item.ocorrenciaId}-${item.contratoItemId}`}><span className="contrato-ordinal">{ordinal(item.ordinal)}</span><div className="contrato-credito-titulo"><strong><IconeServico nome={servico.nome} compacto />{ordinal(item.ordinal)} {servico.nome}</strong><EstadoCredito valor={item.estadoComercial} /></div><CreditoCampo rotulo={item.estadoComercial === 'consumido' ? 'Data de uso' : 'Data agendada'} valor={data(item.data)} /><CreditoCampo rotulo="Atendimento" valor={rotuloStatus(item.statusAtendimento)} /><CreditoCampo rotulo={item.estadoComercial === 'consumido' ? 'Horário realizado' : 'Horário agendado'} valor={item.horarioInicio ? `${item.horarioInicio}${item.horarioFim ? ` → ${item.horarioFim}` : ''}` : '—'} /><i aria-hidden="true">›</i></button>)}</div>
  </div>
}

function NivelCredito({ credito, aposAcao, onClose }: { credito: DetalheUnidadeCredito; aposAcao: () => Promise<void>; onClose: () => void }) {
  const [acao, setAcao] = useState<Acao | null>(null), [motivo, setMotivo] = useState(''), [destino, setDestino] = useState(''), [salvando, setSalvando] = useState(false), [erro, setErro] = useState('')
  const destinos = useMemo(() => ['agendado', 'confirmado', 'recebido', 'em_atendimento', credito.modalidade === 'taxidog' ? 'aguardando_entrega' : 'aguardando_retirada'], [credito.modalidade])
  useEffect(() => { setDestino(destinos.includes(credito.statusAnteriorConclusao ?? '') ? credito.statusAnteriorConclusao! : '') }, [credito.statusAnteriorConclusao, destinos])
  const possuiDecisaoAdministrativa = credito.eventos.some((evento) => ['credito_perdido_falta', 'credito_preservado_falta', 'credito_perdido_encerramento', 'credito_preservado_encerramento'].includes(evento.tipo)), possuiDecisaoEncerramento = credito.eventos.some((evento) => ['credito_perdido_encerramento', 'credito_preservado_encerramento'].includes(evento.tipo))
  function iniciarAcao(nova: NovaAcao) { setAcao({ ...nova, chaveIdempotencia: crypto.randomUUID() }); setMotivo(''); setErro('') }
  async function confirmar() { if (!acao || !motivo.trim() || (acao.tipo === 'reverter' && !destino)) return; setSalvando(true); setErro(''); try { if (acao.tipo === 'reverter') await reverterConclusaoContrato({ atendimentoId: credito.atendimentoId!, statusDestino: destino, motivo: motivo.trim(), chaveIdempotencia: acao.chaveIdempotencia }); else await decidirCreditoContrato({ operacao: acao.operacao, ocorrenciaId: credito.ocorrenciaId, contratoItemId: credito.contratoItemId, versaoEsperada: credito.versao, decisao: acao.decisao, motivo: motivo.trim(), chaveIdempotencia: acao.chaveIdempotencia }); setAcao(null); setMotivo(''); await aposAcao() } catch (e) { setErro(mensagem(e)) } finally { setSalvando(false) } }
  return <div className="contrato-nivel-conteudo">
    <section className="contrato-credito-hero"><IconeServico nome={credito.servicoNome} grande /><div><span>Unidade comercial</span><h2>{ordinal(credito.ordinal)} {credito.servicoNome}</h2><p>{data(credito.data)} <b>•</b> Ciclo {credito.cicloNumero}</p></div><EstadoCredito valor={credito.estadoComercial} /></section>
    <section className="contrato-faixa-resumo tres"><Indicador icone="▣" rotulo="Estado comercial" valor={rotuloCredito(credito.estadoComercial)} /><Indicador icone="✓" rotulo="Atendimento" valor={rotuloStatus(credito.statusAtendimento)} /><Indicador icone="◷" rotulo="Horário" valor={credito.horarioInicio ? `${credito.horarioInicio}${credito.horarioFim ? ` – ${credito.horarioFim}` : ''}` : '—'} /></section>
    {credito.estadoComercial === 'revisao_legado' && <div className="contrato-aviso"><strong>Revisão histórica necessária</strong><span>A 032 não inferiu consumo para este atendimento concluído anteriormente.</span></div>}
    {!acao && <div className="contrato-acoes-contextuais">{credito.estadoComercial === 'aguardando_decisao' && <><Button variant="secondary" onClick={() => iniciarAcao({ tipo: 'credito', operacao: 'decidir_falta', decisao: 'preservar' })}>Preservar crédito</Button><Button onClick={() => iniciarAcao({ tipo: 'credito', operacao: 'decidir_falta', decisao: 'perder' })}>Perder crédito</Button></>}{credito.estadoComercial === 'consumido' && credito.statusAtendimento === 'concluido' && <Button variant="secondary" onClick={() => iniciarAcao({ tipo: 'reverter' })}>Reverter conclusão</Button>}{possuiDecisaoAdministrativa && ['perdido', 'disponivel'].includes(credito.estadoComercial) && <Button variant="secondary" onClick={() => iniciarAcao({ tipo: 'credito', operacao: 'corrigir_decisao', decisao: credito.estadoComercial === 'perdido' ? 'preservar' : 'perder' })}>Corrigir decisão</Button>}{credito.cicloEncerramentoPendente && credito.estadoComercial === 'disponivel' && !possuiDecisaoEncerramento && <><Button variant="secondary" onClick={() => iniciarAcao({ tipo: 'credito', operacao: 'decidir_encerramento', decisao: 'preservar' })}>Preservar no Ciclo</Button><Button onClick={() => iniciarAcao({ tipo: 'credito', operacao: 'decidir_encerramento', decisao: 'perder' })}>Perder no encerramento</Button></>}</div>}
    {acao && <section className="contrato-form-acao"><h3>{acao.tipo === 'reverter' ? 'Reverter conclusão' : acao.decisao === 'perder' ? 'Perder crédito' : 'Preservar crédito'}</h3><p>{acao.tipo === 'reverter' ? 'Os créditos consumidos neste atendimento serão restaurados.' : `Decisão aplicada somente ao crédito de ${credito.servicoNome}.`}</p>{acao.tipo === 'reverter' && <label>Retornar atendimento para<select value={destino} onChange={(e) => setDestino(e.target.value)}><option value="">Selecione</option>{destinos.map((status) => <option value={status} key={status}>{rotuloStatus(status)}</option>)}</select></label>}<label>Motivo *<textarea value={motivo} maxLength={1000} onChange={(e) => setMotivo(e.target.value)} /></label>{erro && <p role="alert">{erro}</p>}<div><Button variant="secondary" disabled={salvando} onClick={() => setAcao(null)}>Cancelar</Button><Button disabled={salvando || !motivo.trim() || (acao.tipo === 'reverter' && !destino)} onClick={() => void confirmar()}>{salvando ? 'Salvando…' : 'Confirmar decisão'}</Button></div></section>}
    <TimelineCredito eventos={credito.eventos} />
    <details className="contrato-detalhes-tecnicos"><summary>▤ <span>Informações técnicas</span><b>⌄</b></summary><p>Ocorrência: {credito.ocorrenciaId}</p><p>Item do contrato: {credito.contratoItemId}</p>{credito.eventos.filter((evento) => evento.responsavelId).map((evento) => <p key={evento.id}>Responsável do evento {evento.id}: {evento.responsavelId}</p>)}</details>
    <footer className="contrato-credito-rodape"><Button variant="secondary" onClick={onClose}>Fechar</Button></footer>
  </div>
}

function TimelineCredito({ eventos }: { eventos: EventoCredito[] }) { return <section className="contrato-timeline"><h3>Histórico do crédito</h3><div>{eventos.map((evento, indice) => { const responsavel = responsavelAmigavel(evento.responsavelId); return <article key={evento.id}><span className={indice === eventos.length - 1 ? 'vazio' : ''} aria-hidden="true">{indice === eventos.length - 1 ? '○' : '●'}</span><time>{dataHora(evento.ocorridoEm)}</time><div><strong>{rotuloEvento(evento.tipo)}</strong><EstadoCredito valor={evento.estadoNovo} /></div>{evento.motivo && <p>{evento.motivo}</p>}{responsavel && <small>Responsável: {responsavel}</small>}</article> })}</div></section> }
function IconeCiclo({ grande = false, compacto = false, renovacao = false }: { grande?: boolean; compacto?: boolean; renovacao?: boolean }) {
  return <span className={`contrato-ciclo-icone ${grande ? 'grande' : ''} ${compacto ? 'compacto' : ''}`} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{renovacao ? <><path d="M6 8h11a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2Z"/><path d="M8 6v4m7-4v4M4 12h15"/><path d="M10 17a3 3 0 0 0 5.2 1.9M16 17a3 3 0 0 0-5.2-1.9"/><path d="m15 18.9.4-1.8 1.6.7M11 15l-.4 1.8-1.6-.7M5 3v2M4 4h2M19 3v2m-1-1h2"/></> : <><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4m8-4v4M4 9h16"/><path d="m9 14 2 2 4-4"/></>}</svg></span>
}
function IconeServico({ nome, grande = false, compacto = false }: { nome: string; grande?: boolean; compacto?: boolean }) {
  const chave = nome.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
  const tipo = chave.includes('hidrat') ? 'hidratacao' : chave.includes('tosa') ? 'tosa' : chave.includes('carding') || chave.includes('groom') || chave.includes('escov') ? 'carding' : chave.includes('taxi') || chave.includes('transport') ? 'transporte' : chave.includes('banho') ? 'banho' : 'outro'
  return <span className={`contrato-servico-icone ${grande ? 'grande' : ''} ${compacto ? 'compacto' : ''}`} data-tipo={tipo} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{tipo === 'banho' ? <><path d="M4 11h16v2a6 6 0 0 1-6 6H9a5 5 0 0 1-5-5v-3Z"/><path d="M7 11V7a3 3 0 0 1 6 0"/><path d="M6 19v2m11-2v2"/><circle cx="17.5" cy="6" r="1"/><circle cx="20" cy="8.5" r=".7"/></> : tipo === 'hidratacao' ? <path d="M12 3S6.5 9.4 6.5 14a5.5 5.5 0 0 0 11 0C17.5 9.4 12 3 12 3Z"/> : tipo === 'tosa' ? <><circle cx="6" cy="17" r="3"/><circle cx="18" cy="17" r="3"/><path d="m8.5 15.5 8-11M15.5 15.5l-8-11"/></> : tipo === 'carding' ? <><path d="M5 7h11v7H5z"/><path d="m16 10 3-2v5l-3-2M8 14v5m3-5v5m3-5v5"/></> : tipo === 'transporte' ? <><path d="M4 16V9l2-4h12l2 4v7"/><path d="M4 11h16M7 16v2m10-2v2"/><circle cx="7" cy="14" r="1"/><circle cx="17" cy="14" r="1"/></> : <><circle cx="12" cy="13" r="3"/><circle cx="6.5" cy="9" r="2"/><circle cx="17.5" cy="9" r="2"/><circle cx="9" cy="5" r="1.5"/><circle cx="15" cy="5" r="1.5"/></>}</svg></span>
}
function Indicador({ icone, rotulo, valor }: { icone: React.ReactNode; rotulo: string; valor: string }) { return <div className="contrato-indicador"><span aria-hidden="true">{icone}</span><div><small>{rotulo}</small><strong>{valor}</strong></div></div> }
function TituloSecao({ titulo }: { titulo: string }) { return <div className="contrato-titulo-secao"><h3>{titulo}</h3><span /></div> }
function BarraSimples({ contagem }: { contagem: Pick<ContagemCreditos, 'consumoPercentual'> }) { return <div className="contrato-barra" aria-label={`${contagem.consumoPercentual}% consumido`}><span style={{ width: `${contagem.consumoPercentual}%` }} /></div> }
function ResumoInline({ contagem }: { contagem: Pick<ContagemCreditos, 'consumidos' | 'disponiveis' | 'perdidos'> }) { return <div className="contrato-resumo-inline"><span><b>{contagem.consumidos}</b> consumidos</span><span><b>{contagem.disponiveis}</b> disponíveis</span>{contagem.perdidos > 0 && <span className="perdidos"><b>{contagem.perdidos}</b> perdidos</span>}</div> }
function ResumoEstrutural({ contagem }: { contagem: Pick<ContagemCreditos, 'consumidos' | 'disponiveis' | 'perdidos'> }) { return <div className="contrato-resumo-estrutural"><span><b>{contagem.consumidos}</b> consumidos</span><span>{contagem.disponiveis} disponíveis</span><span>{contagem.perdidos} perdidos</span></div> }
function CreditoCampo({ rotulo, valor }: { rotulo: string; valor: string }) { return <div className="contrato-credito-campo"><small>{rotulo}</small><strong>{valor}</strong></div> }
function ListaRotina({ contrato }: { contrato: ContratoResumo }) { const dias = ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado']; return <dl className="contrato-rotina"><div><dt>▣ Dia</dt><dd>{dias[contrato.diaSemanaFixo] ?? '—'}</dd></div><div><dt>◷ Horário</dt><dd>{contrato.horarioFixo}</dd></div><div><dt><IconeServico nome="transporte" compacto />Transporte</dt><dd>{contrato.modalidadeTransporte === 'taxidog' ? 'TaxiDog' : 'Sem transporte'}</dd></div><div><dt>↻ Início</dt><dd>{data(contrato.dataAncora)}</dd></div></dl> }
function Estado({ titulo, texto, children }: { titulo: string; texto: string; children?: React.ReactNode }) { return <div className="ux-empty"><div className="ux-empty-icon">◇</div><h2>{titulo}</h2><p>{texto}</p>{children}</div> }
function EstadoCredito({ valor }: { valor: string }) { return <span className={`credito-tag credito-${valor}`}>{rotuloCredito(valor)}</span> }
function TagEstado({ valor }: { valor: string }) { return <span className={`ux-status ${valor === 'concluido' ? 'muted' : valor === 'requer_revisao' ? 'warning' : 'ok'}`}>{valor.replaceAll('_', ' ')}</span> }
function data(valor: string) { if (!valor) return '—'; const [ano, mes, dia] = valor.split('-'); return `${dia}/${mes}/${ano}` }
function dataHora(valor: string) { const d = new Date(valor); return `${d.toLocaleDateString('pt-BR')}  •  ${d.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}` }
function ordinal(numero: number) { return `${numero}º` }
function rotuloStatus(valor: string | null) { return valor ? ({ agendado: 'Agendado', confirmado: 'Confirmado', recebido: 'Recebido', em_atendimento: 'Em atendimento', aguardando_retirada: 'Aguardando retirada', aguardando_entrega: 'Aguardando entrega', concluido: 'Concluído', cancelado: 'Cancelado', faltou: 'Faltou' } as Record<string, string>)[valor] ?? valor : 'Sem atendimento' }
function rotuloCredito(valor: string | null) { return valor ? ({ reservado: 'Reservado', disponivel: 'Disponível', aguardando_decisao: 'Aguardando decisão', revisao_legado: 'Revisão histórica', consumido: 'Consumido', perdido: 'Perdido' } as Record<string, string>)[valor] ?? valor : 'Crédito criado' }
function rotuloEvento(valor: string) { return valor.replaceAll('_', ' ').replace(/^./, (letra) => letra.toUpperCase()) }
function responsavelAmigavel(valor: string | null) { return valor && !/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(valor) ? valor : null }
function unidade(valor: string, quantidade: number) { const nomes: Record<string, [string, string]> = { dia: ['dia', 'dias'], semana: ['semana', 'semanas'], mes: ['mês', 'meses'], ano: ['ano', 'anos'] }; return (nomes[valor] ?? [valor, valor])[quantidade === 1 ? 0 : 1] }
function mensagem(erro: unknown) { return erro instanceof Error ? erro.message : 'Não foi possível concluir a operação.' }
