import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { agregarCreditos, faixaDisponibilidade } from '../../../supabase/functions/_shared/credito-contrato.ts'
import { criarHandlerCreditos } from '../../../supabase/functions/gerenciar-creditos-contrato/handler.ts'

const sql=readFileSync('../banco/032_ciclo_vida_creditos_contrato.sql','utf8')
const ui=readFileSync('src/contratos/DetalheContrato.tsx','utf8')
const uiCompacto=ui.replace(/\s+/g,'')
const cliente=readFileSync('src/contratos/clienteSupabase.ts','utf8')
const lista=readFileSync('src/contratos/Contratos.tsx','utf8')
const consumoUi=readFileSync('src/contratos/ConsumoContrato.tsx','utf8')
const estilos=readFileSync('src/App.css','utf8')
const creditosEdge=readFileSync('../supabase/functions/gerenciar-creditos-contrato/servico.ts','utf8')
const statusEdge=readFileSync('../supabase/functions/alterar-status-atendimento/servico.ts','utf8')
const remarcacao=readFileSync('../supabase/functions/remarcar-atendimento/servico.ts','utf8')
let total=0
async function t(id:string,nome:string,fn:()=>void|Promise<void>){await fn();total++;console.log(`✓ ${id} ${nome}`)}
const estados=(...valores:('reservado'|'disponivel'|'aguardando_decisao'|'revisao_legado'|'consumido'|'perdido')[])=>valores.map(estadoComercial=>({estadoComercial}))

await t('CR01','item novo começa reservado',()=>assert.match(sql,/estado_comercial set default 'reservado'/))
await t('CR02','agendado não consome',()=>assert.doesNotMatch(sql,/new\.status='agendado'[\s\S]{0,120}consumido/))
await t('CR03','confirmado não consome',()=>assert.doesNotMatch(sql,/new\.status='confirmado'[\s\S]{0,120}consumido/))
await t('CR04','recebido não consome',()=>assert.doesNotMatch(sql,/new\.status='recebido'[\s\S]{0,120}consumido/))
await t('CR05','em atendimento não consome',()=>assert.doesNotMatch(sql,/new\.status='em_atendimento'[\s\S]{0,120}consumido/))
await t('CR06','concluído consome',()=>assert.match(sql,/new\.status='concluido'.*v_credito\.estado_comercial in \('reservado','disponivel'\)[\s\S]*v_estado_novo:='consumido'/))
await t('CR07','B+H consome cada item comercial',()=>assert.match(sql,/for v_credito in[\s\S]*contrato_ciclo_ocorrencia_itens[\s\S]*insert into public\.contrato_credito_eventos/))
await t('CR08','dependência sem item não cria consumo',()=>assert.doesNotMatch(sql,/atendimento_servicos[\s\S]*estado_comercial/))
await t('CR09','conclusão repetida não duplica',()=>assert.match(sql,/if new\.status=old\.status then return new/))
await t('CR10','reversão restaura consumido para reservado',()=>assert.match(sql,/old\.status='concluido'[\s\S]*v_credito\.estado_comercial='consumido'[\s\S]*v_estado_novo:='reservado'/))
await t('CR11','reversão exige motivo',()=>assert.match(sql,/v_motivo is null[\s\S]*Informe motivo e status de destino válidos/))
await t('CR12','auditoria anterior é append-only',()=>assert.match(sql,/atendimento_status_eventos_append_only_032/))
await t('CR13','reversão adiciona evento',()=>assert.ok(sql.includes("v_tipo:='reversao_conclusao'")))
await t('CR14','remarcação não altera crédito',()=>assert.ok(!remarcacao.includes('contrato_ciclo_ocorrencia_itens')))
await t('CR15','cancelamento libera crédito',()=>assert.match(sql,/new\.status='cancelado'[\s\S]*v_estado_novo:='disponivel'/))
await t('CR16','cancelamento do pet shop tem a mesma preservação',()=>assert.ok(sql.includes('atendimento_cancelado_credito_liberado')))
await t('CR17','falta aguarda decisão',()=>assert.match(sql,/new\.status='faltou'[\s\S]*v_estado_novo:='aguardando_decisao'/))
await t('CR18','administrador pode perder crédito individual',()=>assert.match(sql,/v_decisao when 'perder' then 'perdido'/))
await t('CR19','perdido não entra em consumo',()=>{const a=agregarCreditos(estados('consumido','perdido','reservado'));assert.equal(a.consumidos,1);assert.equal(a.consumoPercentual,33)})
await t('CR20','administrador pode preservar crédito',()=>assert.match(sql,/when 'perder' then 'perdido' else 'disponivel'/))
await t('CR21','correção acrescenta evento sem apagar',()=>assert.ok(sql.includes("'credito_corrigido_admin'")&&sql.includes('contrato_credito_eventos_append_only_032')))
await t('CR22','fim com saldo gera pendência',()=>assert.match(sql,/encerramento_pendente=v_possui_saldo_ou_pendencia/))
await t('CR23','saldo não é transferido automaticamente',()=>assert.ok(!sql.includes('ciclo_destino_id')&&!sql.includes('transferir_credito')))
await t('CR24','novo Ciclo mantém créditos pelo próprio ciclo_id',()=>assert.match(sql,/contrato_creditos_ciclo_estado_032_idx/))
await t('CR25','agregados gerais são corretos',()=>assert.deepEqual(agregarCreditos(estados('consumido','consumido','perdido','reservado','disponivel','aguardando_decisao')),{contratados:6,consumidos:2,perdidos:1,reservados:1,livres:1,pendentes:1,disponiveis:2,consumoPercentual:33,disponibilidadePercentual:33}))
await t('CR26','agregação por Serviço usa somente suas unidades',()=>{const banho=agregarCreditos(estados('consumido','consumido','perdido','reservado'));assert.deepEqual([banho.contratados,banho.consumidos,banho.perdidos,banho.disponiveis],[4,2,1,1])})
await t('CR27','retry administrativo é idempotente',()=>assert.ok(sql.includes('contrato_credito_operacoes_idempotentes')&&sql.includes('IDEMPOTENCIA_CONFLITANTE')))
await t('CR28','concorrência usa lock e versão',()=>assert.ok(sql.includes("pg_advisory_xact_lock(hashtextextended('credito:operacao:'")&&sql.includes('estado_comercial_versao<>v_versao')))
await t('CR29','status Edge usa RPC atômica',()=>assert.match(statusEdge,/rpc\('alterar_status_atendimento_com_creditos'/))
await t('CR30','faixa de disponibilidade não confunde perda com consumo',()=>{assert.equal(faixaDisponibilidade(agregarCreditos(estados('consumido','perdido'))),'esgotado');assert.equal(faixaDisponibilidade(agregarCreditos(estados('reservado','consumido'))),'atencao')})
const handler=criarHandlerCreditos({validarToken:async token=>token==='interno'?{id:'usuario-interno',app_metadata:{role:'internal'}}:token==='externo'?{id:'usuario-externo',app_metadata:{}}:null,executar:async()=>({status:'carregado'})},new Set(['http://localhost:5173']))
await t('CR31','Edge exige autenticação',async()=>assert.equal((await handler(new Request('http://local',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}))).status,401))
await t('CR32','Edge recusa usuário sem role internal',async()=>assert.equal((await handler(new Request('http://local',{method:'POST',headers:{authorization:'Bearer externo','content-type':'application/json'},body:JSON.stringify({operacao:'resumo_contrato'})}))).status,403))
await t('CR33','Edge aceita usuário internal',async()=>assert.equal((await handler(new Request('http://local',{method:'POST',headers:{authorization:'Bearer interno','content-type':'application/json'},body:JSON.stringify({operacao:'resumo_contrato'})}))).status,200))

await t('UI01','Contrato abre somente nível Contrato',()=>assert.ok(ui.includes("useState<Nivel>('contrato')")&&uiCompacto.includes("nivel==='contrato'")))
await t('UI02','nível Contrato lista Ciclos',()=>assert.ok(ui.includes('className="contrato-ciclos"')))
await t('UI03','Ciclo atual vem primeiro da ordem autoritativa',()=>assert.ok(creditosEdge.includes(".order('numero',{ascending:false})")&&creditosEdge.includes('Number(b.atual)-Number(a.atual)||b.numero-a.numero')&&uiCompacto.includes("item.atual?'atual':''")))
await t('UI04','clicar Ciclo abre nível Ciclo',()=>assert.ok(ui.includes("setNivel('ciclo')")))
await t('UI05','nível Ciclo mostra Serviços',()=>assert.ok(ui.includes('Serviços deste ciclo')))
await t('UI06','nível Ciclo não renderiza unidades',()=>{const trecho=ui.slice(ui.indexOf('function NivelCiclo'),ui.indexOf('function NivelServico'));assert.ok(!trecho.includes('contrato-credito-card'))})
await t('UI07','clicar Serviço abre nível Serviço',()=>assert.ok(ui.includes("setNivel('servico')")))
await t('UI08','Serviço mostra agregados de forma compacta',()=>assert.ok(ui.includes('className="contrato-faixa-resumo quatro"')&&ui.includes('<BarraSimples contagem={servico}')&&ui.includes('contratados')&&ui.includes('consumidos')&&ui.includes('disponíveis')))
await t('UI09','Serviço lista somente suas unidades',()=>assert.ok(ui.includes('servico.unidades.map')))
await t('UI10','PERDIDO possui tag textual',()=>assert.ok(uiCompacto.includes("perdido:'Perdido'")))
await t('UI11','CONSUMIDO possui tag textual',()=>assert.ok(uiCompacto.includes("consumido:'Consumido'")))
await t('UI12','RESERVADO possui tag textual',()=>assert.ok(uiCompacto.includes("reservado:'Reservado'")))
await t('UI13','clicar unidade abre detalhe',()=>assert.ok(ui.includes("setNivel('credito')")))
await t('UI14','histórico mantém ordem retornada',()=>assert.ok(ui.includes('eventos.map((evento, indice)')&&ui.includes('<TimelineCredito eventos={credito.eventos}')&&cliente.includes('carregarDetalheCredito')))
await t('UI15','voltar Unidade para Serviço',()=>assert.ok(uiCompacto.includes("if(nivel==='credito')setNivel('servico')")))
await t('UI16','voltar Serviço para Ciclo',()=>assert.ok(uiCompacto.includes("elseif(nivel==='servico')setNivel('ciclo')")))
await t('UI17','voltar Ciclo para Contrato',()=>assert.ok(uiCompacto.includes("elseif(nivel==='ciclo')setNivel('contrato')")))
await t('UI18','não abre modal sobre modal',()=>assert.equal((ui.match(/<Modal\b/g)??[]).length,1))
await t('UI19','não usa accordion gigante',()=>assert.ok(!ui.includes('<details className="contrato-ciclos"')))
await t('UI20','carregamento é por nível e sem query por card',()=>assert.ok(cliente.includes('resumo_contrato')&&cliente.includes('detalhe_ciclo')&&cliente.includes('detalhe_credito')))
await t('UI21','falta decide cada Serviço individualmente',()=>assert.ok(ui.includes('Decisão aplicada somente ao crédito de ${credito.servicoNome}.')))
await t('UI22','reversão sugere status anterior real',()=>assert.ok(ui.includes('credito.statusAnteriorConclusao')))
await t('UI23','modalidade filtra aguardando entrega ou retirada',()=>assert.ok(uiCompacto.includes("credito.modalidade==='taxidog'?'aguardando_entrega':'aguardando_retirada'")))
await t('UI24','retry preserva a mesma chave idempotente da ação',()=>assert.ok(uiCompacto.includes('chaveIdempotencia:acao.chaveIdempotencia')))
await t('UI25','correção exige decisão administrativa anterior',()=>assert.ok(sql.includes('Não existe decisão administrativa anterior para corrigir.')))
await t('UI26','decisão de encerramento não se repete como nova decisão',()=>assert.ok(sql.includes('DECISAO_JA_REGISTRADA')&&ui.includes('!possuiDecisaoEncerramento')))
await t('UI27','falha da Edge é apresentada de forma recuperável e sanitizada',()=>assert.ok(cliente.includes('Não foi possível acessar os créditos do Contrato. Tente novamente.')&&ui.includes('Tentar novamente')))
await t('UI28','listagem usa grade de cards inteiramente clicáveis e sem CTA textual',()=>assert.ok(lista.includes('className="contrato-card"')&&lista.includes('role="button"')&&lista.includes('tabIndex={0}')&&lista.includes('evento.key === "Enter" || evento.key === " "')&&!lista.includes('Ver contrato')&&estilos.includes('grid-template-columns: repeat(3, minmax(0, 1fr))')&&estilos.includes('.contrato-card:focus-visible')))
await t('UI29','card mostra ciclo atual e consumo autoritativo',()=>assert.ok(lista.includes('Ciclo ${ciclo.numero}')&&lista.includes('<BarraConsumoContrato contagem={ciclo}')&&lista.includes('<ResumoContagemContrato contagem={ciclo}')))
await t('UI30','card mostra consumidos disponíveis e perdidos sem confundir conceitos',()=>assert.ok(consumoUi.includes('consumidos')&&consumoUi.includes('disponíveis')&&consumoUi.includes('perdidos')))
await t('UI31','resumo dos cards carrega dados em lote sem consulta por card',()=>assert.ok(cliente.includes('.in("contrato_id", contratos.map')&&cliente.includes('.in("ciclo_id", cicloIds)')&&!cliente.slice(cliente.indexOf('return contratos.map((contrato) => {')).includes('supabase.from')))
await t('UI32','indisponibilidade da fonte de consumo não derruba a listagem',()=>assert.ok(cliente.includes('consumoDisponivel: false')&&lista.includes('Consumo indisponível neste ambiente')))
await t('UI33','faixas visuais compartilham o agregador autoritativo',()=>assert.ok(consumoUi.includes('faixaDisponibilidade(contagem)')&&estilos.includes('.contrato-consumo.atencao')&&estilos.includes('.contrato-consumo.esgotado')))
await t('UI34','drill-down mantém um único painel progressivo',()=>assert.ok(uiCompacto.includes("typeNivel='contrato'|'ciclo'|'servico'|'credito'")&&((ui.match(/<Modal\b/g)??[]).length===1)))
await t('UI35','grade e painel possuem adaptação móvel sem overflow horizontal',()=>assert.ok(estilos.includes('@media (max-width: 760px)')&&estilos.includes('.contrato-lista { grid-template-columns: 1fr; }')&&estilos.includes('min-width: 0')))
await t('UI36','clique pertence ao card inteiro e não a overlay ou CTA interno',()=>assert.ok(lista.includes('onClick={(evento) => {')&&lista.includes('evento.currentTarget')))
await t('UI37','card ignora controles interativos internos futuros',()=>assert.ok(lista.includes("button, a, input, select, textarea, [role='button'], [data-card-control]")&&lista.includes('controle !== card')))
await t('UI38','card possui cursor hover e foco visível',()=>assert.ok(estilos.includes('cursor: pointer')&&estilos.includes('.contrato-card:hover')&&estilos.includes('.contrato-card:focus-visible')))
await t('UI39','avatar nome consumo valor e espaço livre propagam para o article',()=>assert.ok(lista.includes('<article')&&lista.includes('<div className="avatar"')&&lista.includes('<h2 title={contrato.petNome}')&&lista.includes('<BarraConsumoContrato')&&lista.includes('moeda.format(contrato.valorContratado)')&&!lista.includes('onClick={onOpen}')))
await t('UI40','iconografia semântica identifica serviços nos quatro níveis',()=>assert.ok(ui.includes("tipo === 'banho'")&&ui.includes("tipo === 'hidratacao'")&&ui.includes("tipo === 'tosa'")&&ui.includes("tipo === 'carding'")&&ui.includes("tipo === 'transporte'")&&(ui.match(/<IconeServico\b/g)??[]).length>=7&&estilos.includes('.contrato-servico-icone.grande')))
await t('UI41','Ciclos usam calendário semântico da referência',()=>assert.ok((ui.match(/<IconeCiclo\b/g)??[]).length>=4&&ui.includes('<IconeCiclo renovacao grande />')&&estilos.includes('.contrato-ciclo-icone.grande')))

console.log(`${total} testes do ciclo de vida de créditos passaram.`)
