import { useContext, useEffect, useState } from 'react'
import Button from '../components/ui/Button'
import Modal from '../components/ui/Modal'
import Input from '../components/ui/Input'
import { AgendaContext } from '../context/AgendaContext'
import { SistemaContext } from '../context/SistemaContext'
import { gerenciarPacote, listarPacotes, simularPacote } from '../pacotes/clienteSupabase'
import { descreverRecorrencia, type Pacote, type PacoteServico, type SimulacaoPacote, type UnidadePeriodo } from '../pacotes/contrato'

const moeda = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
const unidades:UnidadePeriodo[]=['dia','semana','mes','ano']

export default function Pacotes(){
 const {servicos}=useContext(AgendaContext),{clientes,pets}=useContext(SistemaContext)
 const [pacotes,setPacotes]=useState<Pacote[]>([]),[estado,setEstado]=useState<'carregando'|'pronto'|'erro'>('carregando'),[erro,setErro]=useState('')
 const [editor,setEditor]=useState<Pacote|null|undefined>(null),[simulando,setSimulando]=useState<Pacote|null>(null),[menu,setMenu]=useState<string|null>(null)
 async function carregar(){setEstado('carregando');try{setPacotes(await listarPacotes());setEstado('pronto')}catch(e){setErro(e instanceof Error?e.message:'Não foi possível carregar os pacotes.');setEstado('erro')}}
 useEffect(()=>{void carregar()},[])
 async function alternar(p:Pacote){setMenu(null);const r=await gerenciarPacote({operacao:'editar',chaveIdempotencia:crypto.randomUUID(),pacoteId:p.id,versaoEsperada:p.versao,nome:p.nome,ativo:!p.ativo,servicos:p.servicos});if(r.status==='salvo')await carregar();else setErro(r.mensagem)}
 return <div className="ux-page pacotes-ux">
  <header className="ux-page-head"><div><span className="ux-eyebrow">Catálogo comercial</span><h1>Pacotes</h1><p>Monte ofertas recorrentes com serviços e condições de preço claras.</p></div><Button onClick={()=>setEditor(undefined)}>+ Novo pacote</Button></header>
  {estado==='carregando'&&<Estado titulo="Carregando pacotes…" texto="Buscando a composição mais recente do catálogo."/>}
  {estado==='erro'&&<Estado titulo="Não foi possível carregar" texto={erro}><Button onClick={()=>void carregar()}>Tentar novamente</Button></Estado>}
  {estado==='pronto'&&pacotes.length===0&&<Estado titulo="Seu catálogo está vazio" texto="Crie o primeiro pacote para começar."/>}
  {estado==='pronto'&&<section className="pacotes-grade">{pacotes.map(p=><article className={`pacote-card ${!p.ativo?'is-inativo':''}`} key={p.id}>
   <div className="pacote-card-top"><span className={`ux-status ${p.ativo?'ok':'muted'}`}>{p.ativo?'Ativo':'Inativo'}</span><div className="ux-menu"><button aria-label={`Mais ações de ${p.nome}`} onClick={()=>setMenu(menu===p.id?null:p.id)}>•••</button>{menu===p.id&&<div className="ux-menu-pop"><button onClick={()=>setSimulando(p)} disabled={!p.configuracaoCompleta}>Simular valores</button><button onClick={()=>void alternar(p)}>{p.ativo?'Desativar':'Reativar'}</button></div>}</div></div>
   <h2>{p.nome}</h2>{p.configuracaoCompleta?<><p className="pacote-composicao">{p.servicos.map(s=>`${s.quantidadePorCiclo}× ${s.servicoNome}`).join(' · ')}</p><div className="pacote-chips">{p.servicos.map(s=><span key={s.id??s.servicoId}>{s.servicoNome}: {descreverRecorrencia(s).toLowerCase()} · {s.descontoPercentual}% de desconto</span>)}</div><strong className="pacote-valor">Preço calculado para cada pet na venda</strong></>:<div className="ux-warning"><b>Requer configuração</b><span>Revise os descontos dos Serviços antes de ativar.</span></div>}
   <footer><span>Atualizado em {new Date(p.atualizadoEm).toLocaleDateString('pt-BR')}</span><Button variant="secondary" onClick={()=>setEditor(p)}>Editar</Button></footer>
  </article>)}</section>}
  {editor!==null&&<Editor pacote={editor} servicos={servicos.filter(s=>s.ativo)} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);await carregar()}}/>}
  {simulando&&<Simulador pacote={simulando} clientes={clientes} pets={pets} onClose={()=>setSimulando(null)}/>} 
 </div>
}

function Estado({titulo,texto,children}:{titulo:string;texto:string;children?:React.ReactNode}){return <div className="ux-empty"><div className="ux-empty-icon">◇</div><h2>{titulo}</h2><p>{texto}</p>{children}</div>}

function Editor({pacote,servicos,onClose,onSaved}:{pacote:Pacote|undefined;servicos:{id:string;nome:string}[];onClose:()=>void;onSaved:()=>void}){
 const [nome,setNome]=useState(pacote?.nome??''),[ativo,setAtivo]=useState(pacote?.ativo??true),[itens,setItens]=useState<PacoteServico[]>(pacote?.servicos??[]),[selecionado,setSelecionado]=useState<number|null>(null),[salvando,setSalvando]=useState(false),[erro,setErro]=useState('')
 function adicionar(id:string){if(itens.some(i=>i.servicoId===id))return;const s=servicos.find(x=>x.id===id);setItens([...itens,{servicoId:id,servicoNome:s?.nome,ordem:itens.length+1,quantidadePorCiclo:1,intervaloQuantidade:1,intervaloUnidade:'semana',offsetInicialQuantidade:0,offsetInicialUnidade:'dia',descontoPercentual:0}]);setSelecionado(itens.length)}
 function atualizar(i:number,p:Partial<PacoteServico>){setItens(v=>v.map((x,n)=>n===i?{...x,...p}:x))}
 function remover(i:number){setItens(v=>v.filter((_,n)=>n!==i).map((x,n)=>({...x,ordem:n+1})));setSelecionado(null)}
 async function salvar(){setErro('');if(!nome.trim()||(!itens.length&&ativo)){setErro('Informe o nome e adicione ao menos um serviço para manter o pacote ativo.');return}setSalvando(true);try{const r=await gerenciarPacote({operacao:pacote?'editar':'criar',chaveIdempotencia:crypto.randomUUID(),pacoteId:pacote?.id,versaoEsperada:pacote?.versao,nome:nome.trim(),ativo,servicos:itens});if(r.status==='salvo')onSaved();else setErro(r.mensagem)}catch(e){setErro(e instanceof Error?e.message:'Não foi possível salvar.')}finally{setSalvando(false)}}
 return <Modal aberto titulo={pacote?'Editar pacote':'Novo pacote'} onClose={onClose} maxWidth="1040px" className="ux-modal"><div className="editor-layout"><main>
  <section className="ux-section"><div className="ux-section-title"><span>1</span><div><h3>Informações do pacote</h3><p>O nome que a equipe verá no catálogo.</p></div></div><label>Nome do pacote<Input value={nome} onChange={e=>setNome(e.target.value)} placeholder="Ex.: Banho em dia"/></label><label className="ux-switch"><input type="checkbox" checked={ativo} onChange={e=>setAtivo(e.target.checked)}/><span/><div><b>Pacote ativo</b><small>Disponível para novas vendas</small></div></label></section>
  <section className="ux-section"><div className="ux-section-title"><span>2</span><div><h3>Serviços incluídos</h3><p>Escolha os serviços e ajuste como cada um participa do ciclo.</p></div></div><div className="servico-add"><select defaultValue="" onChange={e=>{adicionar(e.target.value);e.currentTarget.value='' }}><option value="" disabled>Adicionar um serviço…</option>{servicos.filter(s=>!itens.some(i=>i.servicoId===s.id)).map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></div>
  <div className="servico-card-list">{itens.map((item,i)=><article className="servico-config-card" key={item.id??item.servicoId}><div><span className="servico-ordem">{i+1}</span><div><h4>{item.servicoNome}</h4><p>{item.quantidadePorCiclo} {item.quantidadePorCiclo===1?'atendimento':'atendimentos'} por ciclo · {descreverRecorrencia(item).toLowerCase()}</p><small>{item.descontoPercentual===null?'Desconto ainda não revisado':`${item.descontoPercentual}% de desconto sobre o preço avulso`}</small></div></div><button onClick={()=>setSelecionado(i)}>Configurar</button></article>)}</div>
  {!itens.length&&<div className="ux-inline-empty">Adicione os serviços que formam este pacote.</div>}</section>
 </main><aside className="editor-resumo"><span className="ux-eyebrow">Resumo</span><h3>{nome||'Novo pacote'}</h3><strong>{itens.reduce((n,i)=>n+i.quantidadePorCiclo,0)}</strong><p>serviços contratados por ciclo</p>{itens.map(i=><div key={i.servicoId}><span>{i.quantidadePorCiclo}× {i.servicoNome}</span><b>{i.descontoPercentual===null?'Revisar':`${i.descontoPercentual}% off`}</b></div>)}</aside></div>
 {erro&&<div className="ux-error">{erro}</div>}<div className="ux-modal-footer"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={salvando} onClick={()=>void salvar()}>{salvando?'Salvando…':'Salvar pacote'}</Button></div>
 {selecionado!==null&&itens[selecionado]&&<ConfigServico item={itens[selecionado]} onChange={p=>atualizar(selecionado,p)} onRemove={()=>remover(selecionado)} onClose={()=>setSelecionado(null)}/>}</Modal>
}

function ConfigServico({item,onChange,onRemove,onClose}:{item:PacoteServico;onChange:(p:Partial<PacoteServico>)=>void;onRemove:()=>void;onClose:()=>void}){
 const preset=item.intervaloUnidade==='semana'&&item.intervaloQuantidade===1?'semanal':item.intervaloUnidade==='semana'&&item.intervaloQuantidade===2?'quinzenal':item.intervaloUnidade==='mes'&&item.intervaloQuantidade===1?'mensal':'personalizado'
 function setPreset(v:string){if(v==='semanal')onChange({intervaloQuantidade:1,intervaloUnidade:'semana'});if(v==='quinzenal')onChange({intervaloQuantidade:2,intervaloUnidade:'semana'});if(v==='mensal')onChange({intervaloQuantidade:1,intervaloUnidade:'mes'})}
 return <Modal aberto titulo={`Configurar ${item.servicoNome}`} onClose={onClose} maxWidth="720px" className="ux-modal nested"><div className="config-grid"><label>Quantidade por ciclo<input type="number" min="1" value={item.quantidadePorCiclo} onChange={e=>onChange({quantidadePorCiclo:Number(e.target.value)})}/></label><label>Frequência<select value={preset} onChange={e=>setPreset(e.target.value)}><option value="semanal">Toda semana</option><option value="quinzenal">A cada 2 semanas</option><option value="mensal">Todo mês</option><option value="personalizado">Personalizada</option></select></label></div>
 {preset==='personalizado'&&<div className="config-grid"><label>A cada<input type="number" min="1" value={item.intervaloQuantidade} onChange={e=>onChange({intervaloQuantidade:Number(e.target.value)})}/></label><label>Período<select value={item.intervaloUnidade} onChange={e=>onChange({intervaloUnidade:e.target.value as UnidadePeriodo})}>{unidades.map(u=><option key={u} value={u}>{u}</option>)}</select></label></div>}
 <div className="ux-info">Serão exatamente <b>{item.quantidadePorCiclo} ocorrências</b>, distribuídas {descreverRecorrencia(item).toLowerCase()}.</div>
 <h4>Quando começa no ciclo?</h4><div className="config-grid"><label>Deslocamento inicial<input type="number" min="0" value={item.offsetInicialQuantidade} onChange={e=>onChange({offsetInicialQuantidade:Number(e.target.value)})}/></label><label>Unidade<select value={item.offsetInicialUnidade} onChange={e=>onChange({offsetInicialUnidade:e.target.value as UnidadePeriodo})}>{unidades.map(u=><option key={u}>{u}</option>)}</select></label></div>
 <h4>Benefício do pacote</h4><label>Desconto sobre o preço avulso<div className="percent-input"><input type="number" min="0" max="100" step="0.01" value={item.descontoPercentual??''} onChange={e=>onChange({descontoPercentual:e.target.value===''?null:Number(e.target.value)})}/><span>%</span></div></label>
 <div className="ux-info">Na venda, este desconto será aplicado ao preço oficial de {item.servicoNome} calculado pelo Motor para o pet.</div>
 <div className="ux-modal-footer split"><Button variant="danger" onClick={onRemove}>Remover serviço</Button><Button onClick={onClose}>Concluir configuração</Button></div></Modal>
}

function Simulador({pacote,clientes,pets,onClose}:{pacote:Pacote;clientes:{id:string;nome:string}[];pets:{id:string;clienteId:string;nome:string;porte:string}[];onClose:()=>void}){
 const [clienteId,setClienteId]=useState(''),[petId,setPetId]=useState(''),[resultado,setResultado]=useState<SimulacaoPacote|null>(null),[estado,setEstado]=useState<'idle'|'loading'|'erro'>('idle'),[erro,setErro]=useState(''),[detalhes,setDetalhes]=useState(false)
 const disponiveis=clienteId?pets.filter(p=>p.clienteId===clienteId):pets
 async function calcular(){setEstado('loading');setResultado(null);try{const r=await simularPacote(pacote.id,pacote.versao,petId);if(r.status==='calculado'){setResultado(r.simulacao);setEstado('idle')}else{setErro(r.mensagem);setEstado('erro')}}catch(e){setErro(e instanceof Error?e.message:'Não foi possível calcular.');setEstado('erro')}}
 return <Modal aberto titulo="Simular vantagem do pacote" onClose={onClose} maxWidth="880px" className="ux-modal"><p className="ux-lead">Compare o pacote <b>{pacote.nome}</b> com os valores avulsos oficiais para um pet.</p><div className="simulador-selecao"><label>Cliente<select value={clienteId} onChange={e=>{setClienteId(e.target.value);setPetId('');setResultado(null)}}><option value="">Selecione…</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><label>Pet<select value={petId} onChange={e=>{setPetId(e.target.value);setResultado(null)}}><option value="">Selecione…</option>{disponiveis.map(p=><option key={p.id} value={p.id}>{p.nome} · porte {p.porte}</option>)}</select></label><Button disabled={!petId||estado==='loading'} onClick={()=>void calcular()}>{estado==='loading'?'Calculando…':'Calcular'}</Button></div>{estado==='erro'&&<div className="ux-error">{erro} <button onClick={()=>void calcular()}>Tentar novamente</button></div>}{resultado&&<><div className="valor-cards"><div><span>Avulso</span><strong>{moeda.format(resultado.totalAvulso)}</strong></div><div className="featured"><span>No pacote</span><strong>{moeda.format(resultado.totalPacote)}</strong></div><div className="saving"><span>Economia</span><strong>{moeda.format(resultado.economiaAbsoluta)}</strong><small>{resultado.percentualEconomia?.toLocaleString('pt-BR')}%</small></div></div><button className="details-toggle" onClick={()=>setDetalhes(!detalhes)}>{detalhes?'Ocultar detalhes':'Ver detalhes do cálculo'}</button>{detalhes&&<div className="ux-table-wrap"><table><thead><tr><th>Serviço</th><th>Qtd.</th><th>Desconto</th><th>Avulso unit.</th><th>Pacote unit.</th><th>Economia</th></tr></thead><tbody>{resultado.linhas.map(l=><tr key={l.pacoteServicoId}><td>{l.servicoNome}</td><td>{l.quantidadePorCiclo}</td><td>{l.descontoPercentual}%</td><td>{moeda.format(l.precoAvulsoUnitario)}</td><td>{moeda.format(l.precoPacoteUnitario)}</td><td>{moeda.format(l.economia)}</td></tr>)}</tbody></table></div>}</>}</Modal>
}
