import assert from 'node:assert/strict'
import { readFileSync, writeFileSync } from 'node:fs'
import { analisarArquivos, resumo } from './modelo.ts'
import { aplicarGrupo, aplicarInequivocas, agruparValores, contarCampos, type CampoGrupo } from './grupos.ts'
const racas=[{id:'r1',nome:'Sem raça definida (SRD)',especie:'cao',ativo:true},{id:'r2',nome:'Shih Tzu',especie:'cao',ativo:true},{id:'r3',nome:'2',especie:'cao',ativo:true}]
const cab='id;clienteId;nome;especie;raca;genero;tamanho;pelo;comportamento;castrado\n'
const criar=()=>analisarArquivos('id;nome;telefone\nc;Tutor;11999999999',cab+'a;c;Pet A;Cachorro;Shih-tzu;Macho;Pequeno;Curto;calmo;t\nb;c;Pet B;Cachorro;shih tzu;Macho;Pequeno;Curto;calmo;t',[],'teste',[])
let n=0
function t(nome:string,f:()=>void){f();n++;console.log('OK '+nome)}
t('um grupo normalizado de raça resolve vários pets e preserva originais',()=>{const l=criar(),original=JSON.stringify(l);const g=agruparValores(l,'raca_id',racas);assert.equal(g.length,1);assert.equal(g[0].pets.length,2);const novo=aplicarGrupo(l,'raca_id',g[0].chave,'r2',racas);assert.equal(resumo(novo).petsProntos,2);assert.equal(JSON.stringify(l),original);assert.deepEqual(novo.pets.map(p=>p.original),l.pets.map(p=>p.original))})
for(const [campo,destino] of Object.entries({especie:'cao',sexo:'femea',porte:'medio',pelagem:'longa',temperamento:'moderado',castrado:false}))t('resolução agrupada '+campo,()=>{const l=criar(),c=campo as CampoGrupo;const g=agruparValores(l,c,racas)[0];const novo=aplicarGrupo(l,c,g.chave,destino,racas);assert(novo.pets.every(p=>p.resolvido[c]===destino))})
t('vazios não recebem defaults e exigem seleção explícita',()=>{const l=criar();for(const p of l.pets){p.original.comportamento='';p.resolvido.temperamento=null}const novo=aplicarInequivocas(l,racas);assert(novo.pets.every(p=>p.resolvido.temperamento===null));const g=agruparValores(l,'temperamento',racas)[0];assert.throws(()=>aplicarGrupo(l,'temperamento',g.chave,'calmo',racas));assert.throws(()=>aplicarGrupo(l,'temperamento',g.chave,'calmo',racas,[]));const parcial=aplicarGrupo(l,'temperamento',g.chave,'dificil',racas,['a']);assert.equal(parcial.pets[0].resolvido.temperamento,'dificil');assert.equal(parcial.pets[1].resolvido.temperamento,null);assert.equal(contarCampos(parcial,racas).temperamento,1)})
t('seleção de raça vazia não alcança pets não selecionados',()=>{const l=criar();l.pets.forEach(p=>{p.original.raca='';p.resolvido.raca_id=null});const g=agruparValores(l,'raca_id',racas)[0];const novo=aplicarGrupo(l,'raca_id',g.chave,'r1',racas,['b']);assert.equal(novo.pets[0].resolvido.raca_id,null);assert.equal(novo.pets[1].resolvido.raca_id,'r1')})
t('raça 2 e espécie incompatível são rejeitadas',()=>{const l=criar(),g=agruparValores(l,'raca_id',racas)[0];assert.throws(()=>aplicarGrupo(l,'raca_id',g.chave,'r3',racas));l.pets[0].resolvido.especie='gato';assert.throws(()=>aplicarGrupo(l,'raca_id',g.chave,'r2',racas))})
t('equivalências não sobrescrevem decisões nem mapeiam Micro/manso',()=>{const l=criar();l.pets[0].resolvido.sexo='femea';l.pets[0].original.tamanho='Micro';l.pets[0].resolvido.porte=null;l.pets[0].original.comportamento='manso';l.pets[0].resolvido.temperamento=null;const novo=aplicarInequivocas(l,racas);assert.equal(novo.pets[0].resolvido.sexo,'femea');assert.equal(novo.pets[0].resolvido.porte,null);assert.equal(novo.pets[0].resolvido.temperamento,null)})
t('grupos excluem importados/ignorados/existentes e não alteram clientes',()=>{const l=criar();l.pets[0].internal_id='PET-000001';const g=agruparValores(l,'sexo',racas)[0];assert.equal(g.pets.length,1);assert.throws(()=>aplicarGrupo(l,'sexo',g.chave,'femea',racas,['a']));const novo=aplicarGrupo(l,'sexo',g.chave,'femea',racas);assert.equal(novo.pets[0].resolvido.sexo,'macho');assert.deepEqual(novo.clientes,l.clientes);l.pets[1].decisao_operador='ignorar';assert.equal(agruparValores(l,'sexo',racas).length,0)})
t('mudar espécie invalida raça e recalcula contadores',()=>{let l=criar();l=aplicarGrupo(l,'raca_id',agruparValores(l,'raca_id',racas)[0].chave,'r2',racas);assert.equal(resumo(l).petsProntos,2);l=aplicarGrupo(l,'especie',agruparValores(l,'especie',racas)[0].chave,'gato',racas);assert.equal(resumo(l).petsProntos,0);assert.equal(contarCampos(l,racas).raca_id,2)})
t('revisão agrupada é pura, sem API de persistência',()=>{const codigo=readFileSync(new URL('./grupos.ts',import.meta.url),'utf8');assert.doesNotMatch(codigo,/from ['"].*(supabase|api\.ts)|\.rpc\(|\.insert\(|\.update\(/)})
if(process.argv[2]&&process.argv[3]){
 const catalogo=racas.filter(r=>r.id!=='r2').concat([{id:'srdg',nome:'Sem raça definida (SRD)',especie:'gato',ativo:true}])
 const l=analisarArquivos(readFileSync(process.argv[2],'utf8'),readFileSync(process.argv[3],'utf8'),catalogo,'legado',[])
 const depois=aplicarInequivocas(l,catalogo),grupos=agruparValores(l,'raca_id',catalogo)
 t('CSV real: 383 vínculos, nenhum valor ausente inventado',()=>{assert.equal(resumo(l).vinculos,383);assert.equal(resumo(depois).petsProntos,0);assert.equal(resumo(depois).petsPendentes,383);assert.equal(l.clientes.filter(c=>c.erros.length).length,1)})
 console.log(JSON.stringify({antes:resumo(l),depois:resumo(depois),campos:contarCampos(depois,catalogo),gruposRaca:grupos.length,grupos:grupos.map(g=>({especie:g.especiesOriginais,original:g.originais,quantidade:g.pets.length}))},null,2))
 if(process.argv[4]){const q=(v:string)=>'"'+v.replaceAll('"','""')+'"';writeFileSync(process.argv[4],'\uFEFF'+[['especie_original','raca_original','quantidade'],...grupos.map(g=>[g.especiesOriginais.join(' / '),g.originais.join(' / '),String(g.pets.length)])].map(row=>row.map(q).join(';')).join('\r\n')+'\r\n')}
}
console.log(n+' testes de resolução em lote aprovados.')
