import { supabase } from '../lib/supabase.ts'
import type { IntencaoGerenciarPacote,Pacote,PacoteServico,RespostaGerenciarPacote,RespostaSimulacaoPacote,UnidadePeriodo } from './contrato.ts'
type Linha=Record<string,unknown>
const consulta='id,nome,ativo,versao,created_at,updated_at,pacote_servicos(id,servico_id,ordem_exibicao,quantidade_por_ciclo,intervalo_quantidade,intervalo_unidade,offset_inicial_quantidade,offset_inicial_unidade,desconto_percentual,ativo,servicos(nome))'
export async function listarPacotes():Promise<Pacote[]>{const{data,error}=await supabase.from('pacotes').select(consulta).order('ativo',{ascending:false}).order('nome');if(error)throw new Error('Não foi possível carregar o catálogo de pacotes.');return((data??[])as unknown as Linha[]).map(mapearPacote)}
export async function carregarPacote(id:string):Promise<Pacote>{const{data,error}=await supabase.from('pacotes').select(consulta).eq('id',id).single();if(error||!data)throw new Error('Não foi possível recarregar o pacote.');return mapearPacote(data as unknown as Linha)}
async function token(){const{data,error}=await supabase.auth.getSession();if(error||!data.session?.access_token)throw new Error('Sessão interna obrigatória.');return data.session.access_token}
export async function gerenciarPacote(intencao:IntencaoGerenciarPacote):Promise<RespostaGerenciarPacote>{const{data,error}=await supabase.functions.invoke('gerenciar-pacotes',{body:intencao,headers:{Authorization:`Bearer ${await token()}`}});if(error||!data||typeof data!=='object')throw new Error('Não foi possível salvar o pacote.');return data as RespostaGerenciarPacote}
export async function simularPacote(pacoteId:string,pacoteVersaoEsperada:number,petId:string):Promise<RespostaSimulacaoPacote>{const{data,error}=await supabase.functions.invoke('simular-preco-pacote',{body:{pacoteId,pacoteVersaoEsperada,petId},headers:{Authorization:`Bearer ${await token()}`}});if(error||!data||typeof data!=='object')throw new Error('Não foi possível simular o pacote.');return data as RespostaSimulacaoPacote}
function mapearPacote(l:Linha):Pacote{const itens=(Array.isArray(l.pacote_servicos)?l.pacote_servicos:[]).map(i=>mapearServico(i as Linha)).filter(i=>i.ativo).sort((a,b)=>a.ordem-b.ordem);return{id:String(l.id),nome:String(l.nome),ativo:Boolean(l.ativo),versao:Number(l.versao),configuracaoCompleta:itens.length>0&&itens.every(i=>i.descontoPercentual!==null),servicos:itens,criadoEm:String(l.created_at),atualizadoEm:String(l.updated_at)}}
function mapearServico(l:Linha):PacoteServico&{ativo:boolean}{const s=Array.isArray(l.servicos)?l.servicos[0]as Linha|undefined:l.servicos as Linha|undefined;return{id:String(l.id),servicoId:String(l.servico_id),servicoNome:String(s?.nome??''),ordem:Number(l.ordem_exibicao),quantidadePorCiclo:Number(l.quantidade_por_ciclo),intervaloQuantidade:Number(l.intervalo_quantidade),intervaloUnidade:l.intervalo_unidade as UnidadePeriodo,offsetInicialQuantidade:Number(l.offset_inicial_quantidade),offsetInicialUnidade:l.offset_inicial_unidade as UnidadePeriodo,descontoPercentual:l.desconto_percentual==null?null:Number(l.desconto_percentual),ativo:Boolean(l.ativo)}}
